TECHNICAL_QUESTIONS = [
    "Explain the internal mechanics of garbage collection in your primary programming language.",
    "What are the major trade-offs between monolithic and microservice architectures?",
    "How would you design a rate limiter for a high-traffic public API?",
    "Describe a time you had to optimize a slow-performing database query.",
    "Explain the concept of Eventual Consistency in distributed systems.",
    "How does a hash table work under the hood, and how do you handle collisions?",
    "What are the differences between TCP and UDP, and when would you use each?",
    "Explain the CAP theorem and its implications for database choice.",
    "How would you implement a distributed caching layer?",
    "What is the difference between concurrency and parallelism?",
    "Explain how stateless and stateful authentication differ.",
    "What are the pros and cons of using a NoSQL database over a relational one?",
    "How do you ensure data integrity in a concurrent environment?",
    "Describe the lifecycle of a web request from the browser to the server.",
    "What is dependency injection and how does it improve software architecture?",
    "Explain the concept of Big O notation and why it matters in production.",
    "How would you design a URL shortener service like bit.ly?",
    "What are the key principles of RESTful API design?",
    "Explain how asymmetric encryption works in the context of SSL/TLS.",
    "What strategies do you use for handling database migrations safely?",
    "Describe the differences between an abstract class and an interface.",
    "How would you handle a sudden 10x spike in web traffic to your application?",
    "What is the purpose of message brokers like Kafka or RabbitMQ?",
    "Explain the concept of recursion and its potential pitfalls.",
    "How do you approach writing testable and maintainable code?",
    "What is a memory leak, and how would you identify one in a live system?",
    "Explain the differences between processes and threads.",
    "How does a load balancer decide which server to route traffic to?",
    "What are the benefits of immutable data structures?",
    "Describe your experience with containerization technologies like Docker.",
    "How do you implement and manage feature flags in a large system?",
    "Explain the role of indexes in relational databases and how they affect performance.",
    "What is the difference between a stack and a queue data structure?",
    "How would you design an auto-scaling infrastructure on AWS/GCP/Azure?",
    "Explain the concept of CI/CD and your preferred tools for it.",
    "What is deadlocking, and how do you prevent it in concurrent programming?",
    "Describe a challenging bug you fixed and the methodology you used.",
    "How do you manage secrets and environment variables securely?",
    "What are the core principles of SOLID design?",
    "Explain the differences between symmetric and asymmetric cryptography.",
    "How would you design a real-time chat application like Slack?",
    "What is the purpose of an API Gateway in a microservices architecture?",
    "Explain the event-driven architecture pattern.",
    "How do you handle schema changes in a live NoSQL database?",
    "What is the difference between optimistic and pessimistic locking?",
    "Describe how OAuth 2.0 works for user authorization.",
    "How do you approach profiling and identifying performance bottlenecks?",
    "Explain the concept of closures in JavaScript (or your preferred language).",
    "What are the trade-offs of using GraphQL versus REST?",
    "How would you design a robust logging and monitoring strategy?",
    "Explain the concept of 'fail-fast' in software engineering.",
    "What is a reverse proxy, and why is it used?",
    "Describe your approach to code refactoring in a legacy system.",
    "How do you implement rate limiting strictly at the application level?",
    "What is the role of a Content Delivery Network (CDN) in web performance?",
    "Explain the differences between SQL joins (Inner, Left, Right, Outer).",
    "How would you design a scalable search engine capability for an e-commerce site?",
    "What are the benefits and drawbacks of Serverless computing?",
    "Describe the concept of 'infrastructure as code' (IaC).",
    "How do you ensure zero-downtime deployments?",
    "What is the difference between an optimistic update and a pessimistic update on the client?",
    "Explain how a B-tree index works in database storage.",
    "How would you implement a circuit breaker pattern in a microservice?",
    "What are common strategies for preventing SQL injection and XSS attacks?",
    "Describe the role of a task queue like Celery or Sidekiq.",
    "How do you handle idempotency in API design?",
    "What is the difference between vertical and horizontal scaling?",
    "Explain the concept of consistent hashing and where it's used.",
    "How would you design a system to track millions of analytics events per second?",
    "What are the key differences between websockets and long polling?",
    "Describe the Model-View-Controller (MVC) architectural pattern.",
    "How do you approach managing technical debt in a fast-paced agile environment?",
    "What is the purpose of an Object-Relational Mapper (ORM), and what are its caveats?",
    "Explain how cross-origin resource sharing (CORS) works and why it exists.",
    "How would you implement pagination for a massive database dataset?",
    "What is the 'N+1 query problem', and how do you solve it?",
    "Describe the principles of Twelve-Factor App methodology.",
    "How do you securely store user passwords in a database?",
    "What is the difference between a purely functional programming language and an imperative one?",
    "Explain the role of DNS in web routing.",
    "How would you design a centralized configuration management system?",
    "What is server-side rendering (SSR) vs. client-side rendering (CSR)?",
    "Describe the concept of 'duck typing' in dynamic languages.",
    "How do you handle data partitioning or sharding in large databases?",
    "What are the pros and cons of using a graph database like Neo4j?",
    "Explain the concept of 'blue-green deployments'.",
    "How would you trace a request across multiple microservices?",
    "What is the role of the 'virtual DOM' in modern frontend frameworks?",
    "Describe your strategy for writing robust end-to-end (E2E) tests.",
    "How do you implement graceful degradation in web applications?",
    "What is the purpose of a read replica in a database cluster?",
    "Explain the concept of 'memoization' and provide a use case.",
    "How would you design a priority queue system for background jobs?",
    "What are the differences between static, dynamic, strong, and weak typing?",
    "Describe the concept of memory alignment and padding.",
    "How do you prefer to manage state in complex frontend applications?",
    "What is the role of garbage collection roots in memory management?",
    "Explain the differences between thread-safe and non-thread-safe operations.",
    "How would you architect a globally distributed database system?",
    "What is your approach to assessing and adopting new technologies in a team?"
]

HR_QUESTIONS = [
    "Tell me about a time you had to manage conflicting priorities.",
    "Describe a situation where you had to work with a difficult team member.",
    "How do you handle receiving critical feedback from a manager or peer?",
    "Tell me about your greatest professional failure and what you learned from it.",
    "Give an example of a time you stepped up to a leadership role unexpectedly.",
    "How do you approach learning a completely new technology or tool?",
    "Describe a time you had to persuade a stakeholder to adopt your technical design.",
    "Tell me about a project that fell behind schedule and how you handled it.",
    "How do you prioritize your daily tasks when everything seems urgent?",
    "Give an example of an innovative solution you brought to a team.",
    "Describe a situation where you had to make a decision without all the necessary information.",
    "Tell me about a time you mentored a junior colleague. What approach did you take?",
    "How do you ensure your work aligns with the broader goals of the company?",
    "Give an example of a time you disagreed with your manager's direction. How did you resolve it?",
    "Describe your strategy for dealing with technical debt while still delivering features.",
    "Tell me about a time you had to adapt quickly to a significant change in project scope.",
    "How do you handle stress and prevent burnout during critical deadlines?",
    "Give an example of a time you failed to meet a commitment. What happened next?",
    "Describe a situation where you had to effectively communicate complex technical concepts to a non-technical audience.",
    "Tell me about a cross-functional project you worked on. What were the challenges?",
    "How do you define career success for yourself?",
    "Give an example of a time you went above and beyond the requirements of a task.",
    "Describe your ideal work environment and team culture.",
    "Tell me about a time you proactively identified and solved a problem before it became an issue.",
    "How do you approach giving constructive criticism to a peer?",
    "Give an example of a time your communication skills prevented a mistake.",
    "Describe a situation where you had to compromise on a technical ideal for business reasons.",
    "Tell me about a time you had to learn quickly on the job to save a project.",
    "How do you stay motivated during long, tedious phases of a project?",
    "Give an example of a time you had to enforce a rule or policy you didn't agree with.",
    "Describe a time you recognized a colleague's excellent work and how you acknowledged them.",
    "Tell me about a project where you had to work closely with someone whose working style was very different from yours.",
    "How do you handle situations where a team member is not pulling their weight?",
    "Give an example of a time you had to pivot your strategy midway through a project.",
    "Describe a situation where you effectively managed risk on a project.",
    "Tell me about your process for onboarding into a new codebase or team.",
    "How do you maintain a healthy work-life balance while delivering high performance?",
    "Give an example of a time you championed a new process or tool that improved team efficiency.",
    "Describe a time you had to deliver difficult news to a client or stakeholder.",
    "Tell me about a situation where you had to apologize for a mistake at work.",
    "How do you approach continuous professional development?",
    "Give an example of a time you leveraged data to make a key decision.",
    "Describe a situation where you had to rely on a team to accomplish a goal.",
    "Tell me about a time you successfully negotiated a timeline or resource constraint.",
    "How do you prefer to receive recognition for your work?",
    "Give an example of a time you successfully managed up to a difficult manager.",
    "Describe your approach to documenting your work and sharing knowledge.",
    "Tell me about a time you had to balance quality versus speed of delivery.",
    "How do you handle ambiguity in project requirements?",
    "Give an example of a time you turned a dissatisfied client or stakeholder into an advocate.",
    "Describe a situation where you had to advocate for a customer's or user's needs against internal pushback.",
    "Tell me about a time you took a calculated risk and it paid off (or didn't).",
    "How do you ensure inclusivity and diversity of thought within your team?",
    "Give an example of a time you successfully onboarded a new team member.",
    "Describe a time you had to break down a very complex problem into manageable tasks.",
    "Tell me about a situation where you had to lead a project without formal authority.",
    "How do you evaluate and prioritize user feedback?",
    "Give an example of a time you had to say 'no' to a feature request.",
    "Describe your approach to running effective meetings.",
    "Tell me about a time you successfully pitched a new idea that required budget or resources.",
    "How do you handle transitioning off a project or leaving a team/company?",
    "Give an example of a time you helped resolve a conflict between two other team members.",
    "Describe a situation where you found a creative workaround to a tricky technical limitation.",
    "Tell me about a time you had to step out of your specific role to help the team succeed.",
    "How do you assess if a project was successful after it launches?",
    "Give an example of a time you had to work with external vendors or partners.",
    "Describe your strategy for staying focused in a highly distracting environment.",
    "Tell me about a time your initial assumption about a problem was completely wrong.",
    "How do you decide when to optimize code versus when it is 'good enough'?",
    "Give an example of a time you successfully automated a repetitive manual process.",
    "Describe a situation where you had to explain a major technical failure to leadership.",
    "Tell me about your experience working with agile/scrum methodologies and what you would improve.",
    "How do you handle a situation where you feel your skills are not being fully utilized?",
    "Give an example of a time you took ownership of a critical bug impacting users.",
    "Describe a time you had to unblock yourself when waiting on others.",
    "Tell me about a situation where you had to learn from someone less experienced than you.",
    "How do you prefer to build working relationships with cross-functional teams (e.g., Design, Product)?",
    "Give an example of a time you successfully de-escalated a tense situation.",
    "Describe your approach to handling sudden changes in priorities from leadership.",
    "Tell me about a time you felt really proud of your team's accomplishment.",
    "How do you handle working on a product or feature you don't personally believe in?",
    "Give an example of a time you identified a security or privacy risk and mitigated it.",
    "Describe a situation where you had to quickly absorb a large amount of complex information.",
    "Tell me about a time you successfully navigated office politics to get something done.",
    "How do you ensure you are building products that are accessible to all users?",
    "Give an example of a time you had to 'manage out' a toxic team member (or deal with one).",
    "Describe your philosophy on code reviews and what makes them effective.",
    "Tell me about a time you volunteered for a project outside your comfort zone.",
    "How do you handle long periods of remote or asynchronous work?",
    "Give an example of a time you successfully advocated for the adoption of an open-source tool.",
    "Describe a situation where you had to balance building technical depth versus product breadth.",
    "Tell me about a time you had to quickly recover from a dropped ball or missed detail.",
    "How do you approach setting personal goals for a quarter or year?",
    "Give an example of a time you used your technical skills to help a non-technical department (e.g., Sales, Marketing).",
    "Describe your ideal manager. What qualities are most important to you?",
    "Tell me about a time you had to sacrifice a feature to meet a strict deadline.",
    "How do you handle situations where you strongly disagree with the architectural direction of a project?",
    "Give an example of a time you took the initiative to organize a team-building or knowledge-sharing event.",
    "Describe a situation where you learned a valuable lesson from a junior developer or intern.",
    "Finally, tell me what excites you most about joining our team specifically over other opportunities."
]
