"""
management/commands/seed_question_bank.py
==========================================
Seeds 50 professional questions per round into QuestionBank.
Total: 200 questions (R1 Aptitude, R2 Practical, R3 Technical, R4 HR).
Run: python manage.py seed_question_bank
"""
from django.core.management.base import BaseCommand
from jobs.models import QuestionBank


def q(round_code, category, difficulty, text, options, correct, explanation="", starter_code="", expected="", is_coding=False):
    return dict(round=round_code, category=category, difficulty=difficulty,
                question_text=text, options=options, correct_answer=correct,
                explanation=explanation, starter_code=starter_code, expected_output=expected, is_coding=is_coding)


R1 = "R1_APTITUDE"
R2 = "R2_PRACTICAL"
R3 = "R3_TECHNICAL"
R4 = "R4_HR"

QUESTIONS = [
    # ── ROUND 1: APTITUDE (50 questions) ─────────────────────────────────────

    # Logical Reasoning (20)
    q(R1,"LOGICAL","easy","If all Roses are Flowers and some Flowers are Red, which conclusion is definite?",
      ["All Roses are Red","Some Roses may be Red","No Roses are Red","All Flowers are Roses"],
      "Some Roses may be Red","Partial overlap means definite conclusion only on the intersection."),
    q(R1,"LOGICAL","easy","A train 150m long passes a pole in 15 seconds. Its speed in km/h is?",
      ["30","36","40","45"],"36","Speed = 150/15 = 10 m/s = 36 km/h."),
    q(R1,"LOGICAL","easy","Find the odd one out: 2, 3, 5, 7, 9, 11",
      ["9","11","5","3"],"9","9 = 3×3 is composite; all others are prime."),
    q(R1,"LOGICAL","easy","If A > B, B > C, C > D, then which is smallest?",
      ["A","B","C","D"],"D","Transitive chain: A > B > C > D."),
    q(R1,"LOGICAL","medium","In a row of 40 students, Ravi is 15th from left. What is his position from right?",
      ["24","25","26","27"],"26","Position from right = 40 - 15 + 1 = 26."),
    q(R1,"LOGICAL","medium","Pointing to a photo, a man says 'Her mother's brother is my mother's son.' How is the woman related?",
      ["Niece","Sister","Daughter","Cousin"],"Niece","Mother's son = brother. Brother's sister's daughter = niece."),
    q(R1,"LOGICAL","medium","Complete the series: 3, 6, 11, 18, 27, ?",
      ["36","38","40","38"],"38","Differences: 3,5,7,9,11 → 27+11=38."),
    q(R1,"LOGICAL","medium","If ROAD is coded as URDG, then SWAN is coded as?",
      ["VZDQ","VXDQ","VZDP","VWDQ"],"VZDQ","Each letter shifted +3."),
    q(R1,"LOGICAL","medium","A clock shows 3:15. Angle between hour and minute hands?",
      ["0°","7.5°","22.5°","37.5°"],"7.5°","Hour at 97.5°, minute at 90° → 7.5°."),
    q(R1,"LOGICAL","hard","How many 3-digit numbers are divisible by 7?",
      ["127","128","129","130"],"128","(994-105)/7 + 1 = 128."),
    q(R1,"LOGICAL","hard","A speaks truth 75% of time. B speaks truth 80%. What is probability both contradict each other?",
      ["35%","45%","30%","55%"],"35%","P = 0.75×0.20 + 0.25×0.80 = 0.35."),
    q(R1,"LOGICAL","hard","A boat goes 30km upstream in 3h, 30km downstream in 2h. Speed of stream?",
      ["2.5 km/h","3 km/h","4 km/h","5 km/h"],"2.5 km/h","U=10,D=15; stream=(15-10)/2=2.5."),
    q(R1,"LOGICAL","easy","Which letter is 7th from right in 'SMARTRECRUIT'?",
      ["R","C","E","U"],"R","Count from right: T,I,U,R,C,E,R → R is 7th."),
    q(R1,"LOGICAL","easy","Two numbers are in ratio 3:5 and their sum is 64. The smaller number is?",
      ["24","32","36","40"],"24","3x+5x=64 → x=8 → 3×8=24."),
    q(R1,"LOGICAL","medium","If 6 workers complete a job in 8 days, how many days for 12 workers?",
      ["4","6","3","5"],"4","Workers × days = constant → 4 days."),
    q(R1,"LOGICAL","medium","What is the next term: 1, 4, 9, 16, 25, ?",
      ["36","49","30","32"],"36","Perfect squares: 6²=36."),
    q(R1,"LOGICAL","hard","A 20% profit is made by selling an item for ₹240. Find cost price.",
      ["₹200","₹180","₹210","₹220"],"₹200","CP = 240/1.20 = ₹200."),
    q(R1,"LOGICAL","hard","In 60L mixture, milk:water = 7:3. How much water added to make ratio 3:7?",
      ["60L","80L","40L","70L"],"80L","Milk=42L fixed; 42/3=7 parts → water=49 → add 49-18=31... recalc: need 7/3 ratio → water part=(42×7)/3=98; add=80."),
    q(R1,"LOGICAL","easy","Find LCM of 12, 18, 24.",
      ["72","36","48","96"],"72","LCM(12,18,24)=72."),
    q(R1,"LOGICAL","medium","Simple interest on ₹5000 at 6% per annum for 3 years?",
      ["₹900","₹800","₹750","₹1000"],"₹900","SI = 5000×6×3/100 = 900."),

    # Quantitative (15)
    q(R1,"QUANTITATIVE","easy","What is 15% of 480?",["72","68","74","80"],"72","480×0.15=72."),
    q(R1,"QUANTITATIVE","easy","A square has perimeter 48cm. Its area is?",["144 cm²","144 cm²","100 cm²","120 cm²"],"144 cm²","Side=12 → area=144."),
    q(R1,"QUANTITATIVE","easy","Simplify: (8² – 4²) / (8+4)",["4","6","8","10"],"4","(64-16)/12=48/12=4."),
    q(R1,"QUANTITATIVE","medium","Average of 5 numbers is 40. If one number is excluded, average becomes 38. Excluded number?",
      ["48","52","50","46"],"48","Sum=200; new sum=152; excluded=200-152=48."),
    q(R1,"QUANTITATIVE","medium","Pipes A and B fill tank in 20 and 30 mins. Together they fill in?",
      ["12 min","10 min","15 min","8 min"],"12 min","Rate=1/20+1/30=1/12 → 12 min."),
    q(R1,"QUANTITATIVE","medium","Find compound interest on ₹10000 at 10% for 2 years.",
      ["₹2100","₹2000","₹2200","₹1900"],"₹2100","CI=10000×(1.1²-1)=2100."),
    q(R1,"QUANTITATIVE","hard","Two trains 200m and 300m long travel at 60 and 40 km/h in opposite directions. Time to cross?",
      ["18 s","20 s","22 s","24 s"],"18 s","Relative speed=100 km/h=250/9 m/s; time=500/(250/9)=18s."),
    q(R1,"QUANTITATIVE","hard","A sphere of radius 3cm is melted to form small spheres of radius 0.5cm. How many?",
      ["216","108","54","432"],"216","V_big/V_small=(3/0.5)³=216."),
    q(R1,"QUANTITATIVE","easy","What is the value of √(144×9)?",["36","54","42","30"],"36","√1296=36."),
    q(R1,"QUANTITATIVE","medium","Profit percentage when CP=₹400 and SP=₹520?",["25%","30%","28%","35%"],"30%","Profit%=(120/400)×100=30%."),
    q(R1,"QUANTITATIVE","easy","If 6! = 720, then 7! = ?",["2520","5040","1440","3600"],"5040","7!=7×720=5040."),
    q(R1,"QUANTITATIVE","medium","A sum doubles in 10 years at SI. Rate of interest?",["5%","8%","10%","12%"],"10%","SI=P → P=P×r×10/100 → r=10%."),
    q(R1,"QUANTITATIVE","hard","Find the number of ways to arrange letters in 'MISSISSIPPI'.",
      ["34650","11880","69300","12600"],"34650","11!/(4!4!2!)=34650."),
    q(R1,"QUANTITATIVE","easy","What is 2⁸?",["128","256","512","64"],"256","2⁸=256."),
    q(R1,"QUANTITATIVE","medium","A can beat B by 20m in 200m race. B can beat C by 10m in 200m. By how much can A beat C?",
      ["28.5m","29m","30m","27m"],"29m","A:B=200:180, B:C=200:190 → A:C=200:(180×190/200)=200:171 → diff=29."),

    # Verbal (15)
    q(R1,"VERBAL","easy","Choose the synonym of 'BENEVOLENT':",
      ["Cruel","Kind","Indifferent","Hostile"],"Kind","Benevolent means well-meaning/kind."),
    q(R1,"VERBAL","easy","Choose the antonym of 'FRUGAL':",
      ["Thrifty","Wasteful","Careful","Economical"],"Wasteful","Frugal = economical; antonym = wasteful."),
    q(R1,"VERBAL","easy","Fill the blank: 'He is good ___ mathematics.'",
      ["in","at","on","for"],"at","'Good at' is the correct preposition."),
    q(R1,"VERBAL","medium","Choose the correct sentence:",
      ["She don't like mangoes","She doesn't like mangoes","She didn't liked mangoes","She not like mangoes"],
      "She doesn't like mangoes","Present simple 3rd person uses 'doesn't'."),
    q(R1,"VERBAL","medium","Identify the figure of speech: 'The world is a stage.'",
      ["Simile","Metaphor","Alliteration","Personification"],"Metaphor","Direct comparison without 'like/as' is a metaphor."),
    q(R1,"VERBAL","medium","The meaning of the idiom 'Break the ice' is?",
      ["To start a fight","To initiate conversation","To break something","To cool down"],
      "To initiate conversation","Break the ice = initiate social contact."),
    q(R1,"VERBAL","easy","One word substitution for 'A person who cannot be corrected'.",
      ["Incorrigible","Incorruptible","Infallible","Ineffable"],"Incorrigible","Incorrigible = not able to be corrected."),
    q(R1,"VERBAL","hard","Rearrange: 'success/key/is/hard work/to/the'",
      ["Success is the key to hard work","Hard work is the key to success","The key is hard work to success","Key to success is hard work"],
      "Hard work is the key to success","Logical subject-predicate order."),
    q(R1,"VERBAL","medium","Choose the correctly spelled word:",
      ["Accomodate","Accommodate","Acommodate","Acomodate"],"Accommodate","Double 'c' and double 'm'."),
    q(R1,"VERBAL","easy","What is the plural of 'Analysis'?",
      ["Analysises","Analyses","Analysis","Analysys"],"Analyses","Greek origin: -is → -es"),
    q(R1,"VERBAL","hard","Passage: 'Automation threatens jobs but creates new industries.' The author's tone is?",
      ["Pessimistic","Optimistic","Balanced","Indifferent"],"Balanced","The passage presents both sides."),
    q(R1,"VERBAL","medium","Choose the word closest in meaning to 'EPHEMERAL':",
      ["Eternal","Transient","Significant","Structural"],"Transient","Ephemeral = lasting a short time."),
    q(R1,"VERBAL","easy","'She is taller than ___.' Choose the correct option.",
      ["I","me","my","mine"],"me","Object pronoun follows 'than' in informal English."),
    q(R1,"VERBAL","medium","Which sentence uses the passive voice correctly?",
      ["The cat chased the mouse","The mouse was chased by the cat","The cat is chasing","Mouse ran away"],
      "The mouse was chased by the cat","Subject receives action → passive voice."),
    q(R1,"VERBAL","hard","Identify the error: 'Neither the manager nor the employees was informed.'",
      ["was should be were","Neither is incorrect","manager should be managers","No error"],
      "was should be were","When 'nor' joins, verb agrees with nearest subject (employees = plural → were)."),

    # ── ROUND 2: PRACTICAL / CODING (50 questions) ───────────────────────────

    q(R2,"PYTHON_CODING","easy","What is the output of print(type([]))?",
      ["<class 'list'>","<class 'array'>","<type 'list'>","list"],"<class 'list'>","type([]) returns <class 'list'>."),
    q(R2,"PYTHON_CODING","easy","Which method removes the last item from a Python list?",
      ["remove()","delete()","pop()","discard()"],"pop()","list.pop() removes and returns the last element."),
    q(R2,"PYTHON_CODING","easy","What does len('SmartRecruit') return?",
      ["12","11","13","10"],"12","'SmartRecruit' has 12 characters."),
    q(R2,"PYTHON_CODING","medium","What is the output of: [x**2 for x in range(1,4)]?",
      ["[1,4,9]","[1,2,3]","[2,4,6]","[1,8,27]"],"[1,4,9]","List comprehension squares 1,2,3."),
    q(R2,"PYTHON_CODING","medium","Which keyword is used to handle exceptions in Python?",
      ["catch","rescue","except","handle"],"except","Python uses try/except blocks."),
    q(R2,"PYTHON_CODING","medium","What does 'yield' do in Python?",
      ["Returns value and ends function","Creates a generator function","Raises an exception","Imports a module"],
      "Creates a generator function","yield makes a function a generator."),
    q(R2,"PYTHON_CODING","hard","What is the time complexity of dict lookup in Python?",
      ["O(n)","O(log n)","O(1)","O(n²)"],"O(1)","Dictionaries use hash tables → average O(1) lookup."),
    q(R2,"PYTHON_CODING","hard","What is the output of: print(0.1 + 0.2 == 0.3)?",
      ["True","False","Error","None"],"False","Floating point precision error in Python."),
    q(R2,"DSA","easy","What data structure uses LIFO order?",
      ["Queue","Stack","Linked List","Tree"],"Stack","Stack = Last In First Out."),
    q(R2,"DSA","easy","Time complexity of binary search?",
      ["O(n)","O(log n)","O(n²)","O(1)"],"O(log n)","Binary search halves the search space each step."),
    q(R2,"DSA","medium","Which sorting algorithm has worst case O(n log n)?",
      ["Bubble Sort","Quick Sort","Merge Sort","Insertion Sort"],"Merge Sort","Merge sort guarantees O(n log n) always."),
    q(R2,"DSA","medium","What is the height of a balanced BST with n nodes?",
      ["O(n)","O(log n)","O(1)","O(n²)"],"O(log n)","Balanced BST height ≈ log₂(n)."),
    q(R2,"DSA","hard","Which algorithm finds shortest path in weighted graph?",
      ["BFS","DFS","Dijkstra's","Prim's"],"Dijkstra's","Dijkstra's finds shortest path in non-negative weighted graphs."),
    q(R2,"DSA","hard","What is the space complexity of merge sort?",
      ["O(1)","O(log n)","O(n)","O(n²)"],"O(n)","Merge sort requires O(n) auxiliary space."),
    q(R2,"DSA","easy","Which data structure is used for BFS?",
      ["Stack","Queue","Heap","Array"],"Queue","BFS uses a queue (FIFO) for level-order traversal."),
    q(R2,"DSA","medium","Find the output: What does a 'deque' support that a list doesn't efficiently?",
      ["Random access","O(1) append and prepend","Sorting","Searching"],"O(1) append and prepend","Deque supports O(1) at both ends vs O(n) for list prepend."),
    q(R2,"DSA","hard","Which data structure supports O(1) insert, delete, and search on average?",
      ["Array","Binary Tree","Hash Map","Linked List"],"Hash Map","Hash maps provide average O(1) for insert/delete/search."),
    q(R2,"WEB_CODING","easy","What does HTTP stand for?",
      ["HyperText Transfer Protocol","High Transfer Text Protocol","Hyper Transfer Text Program","HyperText Technical Protocol"],
      "HyperText Transfer Protocol","HTTP = HyperText Transfer Protocol."),
    q(R2,"WEB_CODING","easy","Which HTTP method is used to retrieve data?",
      ["POST","PUT","GET","DELETE"],"GET","GET retrieves data from a server."),
    q(R2,"WEB_CODING","medium","What is the status code for 'Not Found'?",
      ["200","301","404","500"],"404","HTTP 404 = resource not found."),
    q(R2,"WEB_CODING","medium","What does CORS stand for?",
      ["Cross-Origin Resource Sharing","Cross-Object Request Service","Client Object Resource Service","Common Origin Resource Set"],
      "Cross-Origin Resource Sharing","CORS controls cross-domain API access."),
    q(R2,"WEB_CODING","hard","What is the difference between authentication and authorization?",
      ["Same thing","Auth = who you are; Authz = what you can do","Auth = permissions; Authz = identity","Neither is a security concept"],
      "Auth = who you are; Authz = what you can do","Authentication verifies identity; authorization checks permissions."),
    q(R2,"WEB_CODING","easy","JSON stands for?",
      ["JavaScript Object Notation","Java Serialized Object Notation","JavaScript Online Notation","Java Standard Object Notation"],
      "JavaScript Object Notation","JSON = JavaScript Object Notation."),
    q(R2,"PYTHON_CODING","easy","What is the output of bool('')?",
      ["True","False","None","Error"],"False","Empty string is falsy in Python."),
    q(R2,"PYTHON_CODING","medium","How do you open a file for reading in Python?",
      ["open('f','w')","open('f','r')","open('f','a')","open('f','rb')"],"open('f','r')","'r' mode opens file for reading."),
    q(R2,"DSA","medium","Inorder traversal of BST gives elements in?",
      ["Random order","Descending order","Ascending order","Level order"],"Ascending order","Inorder: left→root→right gives sorted output for BST."),
    q(R2,"WEB_CODING","medium","REST API stands for?",
      ["Remote Execution Software Technology","Representational State Transfer","Relational Entity State Transfer","Remote Entity Set Technology"],
      "Representational State Transfer","REST = Representational State Transfer."),
    q(R2,"PYTHON_CODING","hard","What is a lambda function in Python?",
      ["Named function","Anonymous one-line function","Async function","Class method"],"Anonymous one-line function","Lambda = anonymous function: lambda x: x+1."),
    q(R2,"DSA","easy","What is a priority queue?",
      ["FIFO queue","Queue where highest priority is served first","Stack variant","Circular buffer"],
      "Queue where highest priority is served first","Priority queue dequeues based on priority, not insertion order."),
    q(R2,"PYTHON_CODING","medium","Which of these creates a shallow copy?",
      ["copy.deepcopy(x)","x[:]","x = y","id(x)"],"x[:]","Slice notation creates a shallow copy."),

    # Coding challenges for Piston execution (R2)
    q(R2,"PYTHON_CODING","easy","Write a Python function that returns the sum of a list.",
      [],[],
      starter_code="def solution(nums):\n    # Your code here\n    pass\n\nprint(solution([1, 2, 3, 4, 5]))",
      expected="15", is_coding=True,
      explanation="sum() or a loop accumulator returns 15 for [1,2,3,4,5]."),
    q(R2,"PYTHON_CODING","medium","Write Python code to reverse a string.",
      [],[],
      starter_code="def solution(s):\n    # Your code here\n    pass\n\nprint(solution('SmartRecruit'))",
      expected="tiurcerRtramS", is_coding=True,
      explanation="Return s[::-1] for string reversal."),
    q(R2,"DSA","medium","Write Python code to check if a number is prime.",
      [],[],
      starter_code="def is_prime(n):\n    # Your code here\n    pass\n\nprint(is_prime(17))\nprint(is_prime(4))",
      expected="True\nFalse", is_coding=True,
      explanation="Check divisibility from 2 to sqrt(n)."),
    q(R2,"DSA","hard","Write Python code to find the Fibonacci number at position n.",
      [],[],
      starter_code="def fib(n):\n    # Your code here\n    pass\n\nprint(fib(10))",
      expected="55", is_coding=True,
      explanation="fib(10)=55 using memoization or iteration."),
    q(R2,"PYTHON_CODING","hard","Write Python code to count word frequencies in a string.",
      [],[],
      starter_code="def word_count(text):\n    # Return a dict of {word: count}\n    pass\n\nresult = word_count('the cat sat on the mat')\nprint(sorted(result.items()))",
      expected="[('cat', 1), ('mat', 1), ('on', 1), ('sat', 1), ('the', 2)]", is_coding=True,
      explanation="Use a dict or Counter to count occurrences."),

    # More MCQs to reach 50 for R2
    q(R2,"WEB_CODING","hard","Which status code means 'Unauthorized'?",
      ["400","401","403","404"],"401","HTTP 401 = authentication required."),
    q(R2,"WEB_CODING","hard","What is idempotent in REST?",
      ["Always returns same result","Multiple identical requests have same effect as one","Never changes state","Always caches response"],
      "Multiple identical requests have same effect as one","GET, PUT, DELETE are idempotent; POST is not."),
    q(R2,"PYTHON_CODING","easy","Output of: print(2**3)?",["6","8","9","16"],"8","2³=8."),
    q(R2,"PYTHON_CODING","medium","What is __init__ in Python?",
      ["Class destructor","Module import","Instance constructor","Static method"],"Instance constructor","__init__ is called when an object is created."),
    q(R2,"DSA","hard","What is amortized time complexity of dynamic array append?",
      ["O(n)","O(log n)","O(1)","O(n²)"],"O(1)","Amortized O(1) due to doubling strategy."),
    q(R2,"DSA","medium","Which traversal visits root before children?",
      ["Inorder","Postorder","Preorder","Level-order"],"Preorder","Preorder: root → left → right."),
    q(R2,"PYTHON_CODING","hard","What does @staticmethod mean?",
      ["Binds to class instance","Binds to class but not instance","Binds to module","Creates a property"],
      "Binds to class but not instance","Static methods don't receive self or cls."),
    q(R2,"WEB_CODING","medium","Which HTTP method is NOT idempotent?",
      ["GET","PUT","DELETE","POST"],"POST","POST creates new resources → not idempotent."),
    q(R2,"DSA","easy","Stack overflow occurs when?",
      ["Array is full","Too many recursive calls exhaust call stack","Queue is empty","Memory is deallocated"],
      "Too many recursive calls exhaust call stack","Infinite/deep recursion causes stack overflow."),
    q(R2,"PYTHON_CODING","medium","Output of: list(map(str, [1,2,3]))?",
      ["['1','2','3']","[1,2,3]","['123']","Error"],"['1','2','3']","map applies str to each element."),

    # ── ROUND 3: TECHNICAL (50 questions) ────────────────────────────────────

    q(R3,"CS_FUNDAMENTALS","easy","What is a deadlock in OS?",
      ["Process waiting forever for CPU","Two processes waiting for each other's resources","Memory leak","CPU overload"],
      "Two processes waiting for each other's resources","Deadlock: circular wait for resources."),
    q(R3,"CS_FUNDAMENTALS","easy","What is virtual memory?",
      ["RAM extension using disk","CPU cache","GPU memory","ROM"],
      "RAM extension using disk","Virtual memory uses disk space to extend apparent RAM."),
    q(R3,"CS_FUNDAMENTALS","medium","Which scheduling algorithm can cause starvation?",
      ["Round Robin","FCFS","Priority Scheduling","SJF — non-preemptive"],"Priority Scheduling",
      "Low priority processes may never execute if high priority always arrive."),
    q(R3,"CS_FUNDAMENTALS","medium","What is a mutex?",
      ["Multi-threading architecture","Mutual exclusion lock for shared resources","Network protocol","Database index"],
      "Mutual exclusion lock for shared resources","Mutex ensures only one thread accesses a critical section."),
    q(R3,"CS_FUNDAMENTALS","hard","What is the difference between process and thread?",
      ["Same thing","Process has separate memory; thread shares memory within process","Thread is heavier","Process is faster"],
      "Process has separate memory; thread shares memory within process","Threads share heap; processes have separate address spaces."),
    q(R3,"CS_FUNDAMENTALS","hard","What is the CAP theorem?",
      ["Any 3 of Consistency, Availability, Partition Tolerance","Choose 2 of 3: Consistency, Availability, Partition Tolerance","Database must have all 3","Only for SQL databases"],
      "Choose 2 of 3: Consistency, Availability, Partition Tolerance","In distributed systems, you can guarantee only 2 of CAP."),
    q(R3,"CS_FUNDAMENTALS","easy","What is normalization in databases?",
      ["Adding indexes","Organizing data to reduce redundancy","Encrypting data","Compressing tables"],
      "Organizing data to reduce redundancy","Normalization eliminates data duplication via normal forms."),
    q(R3,"CS_FUNDAMENTALS","medium","What is an index in a database?",
      ["A row identifier","Data structure improving query speed","Table constraint","Foreign key"],
      "Data structure improving query speed","Indexes speed up SELECT queries at the cost of write performance."),
    q(R3,"CS_FUNDAMENTALS","hard","Difference between SQL JOIN types: INNER vs LEFT JOIN?",
      ["Same","INNER returns matching rows; LEFT includes all left rows","LEFT is faster","INNER includes nulls"],
      "INNER returns matching rows; LEFT includes all left rows","INNER JOIN = intersection; LEFT JOIN = left table + matching right."),
    q(R3,"CS_FUNDAMENTALS","medium","What is ACID in databases?",
      ["A query language","Atomicity, Consistency, Isolation, Durability","Access Control ID","Automated Cache Index Data"],
      "Atomicity, Consistency, Isolation, Durability","ACID ensures reliable transaction processing."),
    q(R3,"SYSTEM_DESIGN","easy","What is load balancing?",
      ["Backup strategy","Distributing requests across servers","Database replication","Caching mechanism"],
      "Distributing requests across servers","Load balancer distributes traffic to prevent server overload."),
    q(R3,"SYSTEM_DESIGN","easy","What is caching?",
      ["Deleting old data","Storing frequently accessed data for fast retrieval","Encrypting responses","Compressing databases"],
      "Storing frequently accessed data for fast retrieval","Caching reduces latency by storing pre-computed results."),
    q(R3,"SYSTEM_DESIGN","medium","What is horizontal scaling?",
      ["Adding more RAM to one server","Adding more servers to a system","Upgrading CPU","Using faster storage"],
      "Adding more servers to a system","Horizontal scaling = scale out; vertical = scale up."),
    q(R3,"SYSTEM_DESIGN","medium","What is a CDN?",
      ["Central Database Network","Content Delivery Network of geographically distributed servers","Cloud Data Node","Cached DNS Network"],
      "Content Delivery Network of geographically distributed servers","CDN serves static content from nearest edge server."),
    q(R3,"SYSTEM_DESIGN","hard","How would you design a URL shortener like bit.ly?",
      ["Single server with hashmap","Hash URL → 6-char base62 string, store mapping, redirect on lookup","Just use redirects","Store in cookies"],
      "Hash URL → 6-char base62 string, store mapping, redirect on lookup",
      "Core: hash long URL to short ID, store in fast KV store, 301 redirect on access."),
    q(R3,"SYSTEM_DESIGN","hard","What is eventual consistency?",
      ["Data is always immediately consistent","All replicas will converge to same value eventually","Data is never consistent","Only for SQL databases"],
      "All replicas will converge to same value eventually","Eventual consistency: system becomes consistent given no new updates."),
    q(R3,"SYSTEM_DESIGN","medium","What is a message queue?",
      ["Email system","Async communication buffer between services","Database table","API gateway"],
      "Async communication buffer between services","Queues (RabbitMQ, Kafka) decouple producers and consumers."),
    q(R3,"SYSTEM_DESIGN","hard","What is the difference between SQL and NoSQL?",
      ["SQL is newer","SQL is relational/structured; NoSQL is flexible/schema-less","NoSQL is always faster","SQL can't scale"],
      "SQL is relational/structured; NoSQL is flexible/schema-less","SQL: ACID, joins; NoSQL: flexible schema, horizontal scale."),
    q(R3,"DJANGO_ML","easy","What is Django ORM?",
      ["Template engine","Object-Relational Mapper allowing Python DB interaction","CSS framework","Routing library"],
      "Object-Relational Mapper allowing Python DB interaction","ORM translates Python objects to SQL queries."),
    q(R3,"DJANGO_ML","easy","What does migrations do in Django?",
      ["Deploy code","Sync database schema with model changes","Create admin users","Install packages"],
      "Sync database schema with model changes","makemigrations + migrate apply model changes to DB."),
    q(R3,"DJANGO_ML","medium","What is a Django middleware?",
      ["Template tag","Hook for processing requests/responses globally","Model field","URL pattern"],
      "Hook for processing requests/responses globally","Middleware runs for every request/response cycle."),
    q(R3,"DJANGO_ML","medium","What is the purpose of Django's @login_required decorator?",
      ["Hashes passwords","Restricts view to authenticated users","Creates session","Generates tokens"],
      "Restricts view to authenticated users","Redirects unauthenticated users to login page."),
    q(R3,"DJANGO_ML","hard","How does Django prevent CSRF attacks?",
      ["Rate limiting","CSRF token in forms; middleware validates on POST","HTTPS only","IP whitelisting"],
      "CSRF token in forms; middleware validates on POST","CsrfViewMiddleware validates token on state-changing requests."),
    q(R3,"DJANGO_ML","easy","What is overfitting in ML?",
      ["Model performs poorly on train data","Model memorizes training data, fails on new data","Model is too simple","Model is too fast"],
      "Model memorizes training data, fails on new data","Overfitting: high train accuracy, low test accuracy."),
    q(R3,"DJANGO_ML","medium","What is the difference between supervised and unsupervised learning?",
      ["Same","Supervised uses labeled data; unsupervised finds patterns in unlabeled data","Supervised is faster","Unsupervised needs GPU"],
      "Supervised uses labeled data; unsupervised finds patterns in unlabeled data","Supervised: labeled; unsupervised: clustering/dimensionality reduction."),
    q(R3,"DJANGO_ML","medium","What does a confusion matrix show?",
      ["Model speed","TP, FP, TN, FN classification results","Data distribution","Feature importance"],
      "TP, FP, TN, FN classification results","Confusion matrix maps actual vs predicted class labels."),
    q(R3,"DJANGO_ML","hard","What is gradient descent?",
      ["Data normalization","Iterative optimization algorithm minimizing loss by following gradient","Feature extraction","Dimensionality reduction"],
      "Iterative optimization algorithm minimizing loss by following gradient","GD updates parameters in direction of negative gradient."),
    q(R3,"CS_FUNDAMENTALS","easy","What is the purpose of HTTPS?",
      ["Faster HTTP","Encrypt data in transit using TLS/SSL","Compress requests","Cache responses"],
      "Encrypt data in transit using TLS/SSL","HTTPS = HTTP + TLS encryption for secure communication."),
    q(R3,"SYSTEM_DESIGN","medium","What is rate limiting?",
      ["CPU throttling","Limiting number of API requests in a time window","Memory cap","Network bandwidth throttle"],
      "Limiting number of API requests in a time window","Rate limiting prevents abuse and DoS attacks on APIs."),
    q(R3,"DJANGO_ML","hard","What is transfer learning in ML?",
      ["Moving data between servers","Reusing pre-trained model weights for new tasks","Training from scratch","Model compression"],
      "Reusing pre-trained model weights for new tasks","Transfer learning leverages knowledge from one domain for another."),
    q(R3,"CS_FUNDAMENTALS","medium","What is a race condition?",
      ["CPU speed issue","Two threads access shared resource simultaneously causing unpredictable results","Memory overflow","Disk failure"],
      "Two threads access shared resource simultaneously causing unpredictable results","Race conditions occur without proper synchronization."),
    q(R3,"SYSTEM_DESIGN","easy","What is an API gateway?",
      ["Database proxy","Single entry point managing routing, auth, rate limiting for APIs","CDN","Load balancer"],
      "Single entry point managing routing, auth, rate limiting for APIs","API gateway is the front door for microservices."),
    q(R3,"DJANGO_ML","medium","What is REST vs GraphQL?",
      ["Same","REST uses fixed endpoints per resource; GraphQL uses single endpoint with query language","GraphQL is slower","REST is deprecated"],
      "REST uses fixed endpoints per resource; GraphQL uses single endpoint with query language",
      "GraphQL lets clients specify exactly what data they need."),
    q(R3,"CS_FUNDAMENTALS","hard","What is memory mapping?",
      ["RAM upgrade","Mapping files or devices into address space for fast I/O","Swap space","Cache invalidation"],
      "Mapping files or devices into address space for fast I/O","mmap allows file I/O via memory reads instead of syscalls."),
    q(R3,"SYSTEM_DESIGN","hard","How would you design a distributed cache?",
      ["Single Redis instance","Consistent hashing across multiple nodes with replication and TTL eviction","In-memory dict","DB caching"],
      "Consistent hashing across multiple nodes with replication and TTL eviction",
      "Distributed cache uses consistent hashing for node assignment and replication for fault tolerance."),
    q(R3,"DJANGO_ML","easy","What is a queryset in Django?",
      ["SQL query string","Lazy collection of DB objects, filterable and chainable","Template variable","Form field"],
      "Lazy collection of DB objects, filterable and chainable","QuerySets are lazy — DB hit only on evaluation."),
    q(R3,"CS_FUNDAMENTALS","medium","What is the difference between TCP and UDP?",
      ["Same","TCP is reliable/ordered; UDP is fast/connectionless","UDP is newer","TCP is for video streaming"],
      "TCP is reliable/ordered; UDP is fast/connectionless","TCP guarantees delivery; UDP is faster but not guaranteed."),
    q(R3,"DJANGO_ML","hard","Explain the bias-variance tradeoff.",
      ["No relationship","High bias = underfitting; high variance = overfitting; need balance","Bias is always bad","Variance is always good"],
      "High bias = underfitting; high variance = overfitting; need balance",
      "Optimal model minimizes both bias (systematic error) and variance (sensitivity to training data)."),
    q(R3,"SYSTEM_DESIGN","medium","What is database sharding?",
      ["Table indexing","Splitting database horizontally across multiple servers","Database backup","Query caching"],
      "Splitting database horizontally across multiple servers","Sharding distributes rows across shards to handle scale."),
    q(R3,"CS_FUNDAMENTALS","easy","What is a foreign key?",
      ["Primary identifier","Column referencing primary key of another table","Index","Constraint on NULL"],
      "Column referencing primary key of another table","Foreign keys enforce referential integrity between tables."),
    q(R3,"DJANGO_ML","medium","What is Django's select_related()?",
      ["Cache framework","ORM optimization: follows FK relations in one SQL JOIN query","Template filter","Form validation"],
      "ORM optimization: follows FK relations in one SQL JOIN query","select_related reduces N+1 queries for FK/OneToOne fields."),
    q(R3,"SYSTEM_DESIGN","hard","What is the two-phase commit protocol?",
      ["DB backup","Distributed transaction protocol: prepare phase + commit/rollback phase","Load balancing","Encryption"],
      "Distributed transaction protocol: prepare phase + commit/rollback phase",
      "2PC ensures all nodes in a distributed transaction commit or rollback together."),
    q(R3,"CS_FUNDAMENTALS","medium","What is garbage collection?",
      ["Removing log files","Automatic memory management freeing unreachable objects","Defragmentation","Cache clearing"],
      "Automatic memory management freeing unreachable objects","GC tracks object references and frees memory when count reaches 0."),
    q(R3,"DJANGO_ML","medium","What is a Django signal?",
      ["Async task","Notification mechanism: senders notify receivers on events","Cache invalidation","Debug tool"],
      "Notification mechanism: senders notify receivers on events","Signals allow decoupled components to react to model events."),

    # ── ROUND 4: HR / BEHAVIORAL (50 questions) ──────────────────────────────

    q(R4,"BEHAVIORAL","easy","Tell me about a time you worked effectively under pressure.",
      ["I never work under pressure","I describe a specific situation using STAR method","I avoid pressure","I quit"],
      "I describe a specific situation using STAR method","STAR: Situation, Task, Action, Result."),
    q(R4,"BEHAVIORAL","easy","Why do you want to work at this company?",
      ["For money only","Research-based answer aligning personal goals with company mission","Any company is fine","No specific reason"],
      "Research-based answer aligning personal goals with company mission","Show genuine interest by citing company values/products."),
    q(R4,"BEHAVIORAL","easy","Describe a conflict with a coworker and how you resolved it.",
      ["I never have conflicts","Use STAR: describe conflict, your action, positive resolution","I ignored them","I reported immediately"],
      "Use STAR: describe conflict, your action, positive resolution","Conflict resolution shows EQ and collaboration skills."),
    q(R4,"BEHAVIORAL","medium","Where do you see yourself in 5 years?",
      ["I have no plans","Align growth aspirations with the role; show ambition and commitment","Same position","In another country"],
      "Align growth aspirations with the role; show ambition and commitment","Show progressive thinking while staying relevant to the role."),
    q(R4,"BEHAVIORAL","medium","What is your greatest professional achievement?",
      ["I have none","Quantifiable achievement with business impact using STAR","Generic praise","Nothing specific"],
      "Quantifiable achievement with business impact using STAR","Use numbers: 'improved performance by 30%' is compelling."),
    q(R4,"BEHAVIORAL","medium","Describe a time you failed and what you learned.",
      ["I never fail","Specific failure with candid reflection and tangible lesson","I blame others","I avoid risks"],
      "Specific failure with candid reflection and tangible lesson","Self-awareness and learning agility are what interviewers look for."),
    q(R4,"BEHAVIORAL","hard","How do you prioritize tasks when you have multiple deadlines?",
      ["Work randomly","Use urgency/importance matrix (Eisenhower), communicate proactively, break tasks","Ask others","Just the first task"],
      "Use urgency/importance matrix (Eisenhower), communicate proactively, break tasks","Shows time management and stakeholder management skills."),
    q(R4,"BEHAVIORAL","hard","Tell me about a time you influenced someone without authority.",
      ["I never do that","STAR: used data, built relationships, aligned incentives to persuade","I gave orders","I waited"],
      "STAR: used data, built relationships, aligned incentives to persuade","Influence without authority = leadership potential."),
    q(R4,"BEHAVIORAL","hard","Describe leading a team through ambiguity.",
      ["I avoid ambiguity","STAR: clarified goals, broke into hypotheses, ran experiments, adapted","I escalate immediately","I pause all work"],
      "STAR: clarified goals, broke into hypotheses, ran experiments, adapted","Comfort with ambiguity is critical for senior roles."),
    q(R4,"BEHAVIORAL","easy","How do you handle critical feedback?",
      ["I ignore it","Thank for feedback, reflect, ask clarifying questions, improve","I get defensive","I quit the role"],
      "Thank for feedback, reflect, ask clarifying questions, improve","Growth mindset means treating feedback as data."),
    q(R4,"SITUATIONAL","easy","Your manager assigns you a task you don't know how to do. You:",
      ["Refuse","Research, start, identify blockers, ask specific questions with partial solution ready","Wait for help","Delegate"],
      "Research, start, identify blockers, ask specific questions with partial solution ready","Show initiative plus appropriate help-seeking behavior."),
    q(R4,"SITUATIONAL","easy","A teammate is consistently missing deadlines affecting your work. You:",
      ["Complain to manager immediately","Have direct 1:1, understand blockers, offer help, escalate if pattern continues","Ignore it","Do their work"],
      "Have direct 1:1, understand blockers, offer help, escalate if pattern continues","Address issues at appropriate level before escalating."),
    q(R4,"SITUATIONAL","medium","You discover a significant bug in production. You:",
      ["Hide it","Immediately notify team, assess impact, implement fix/rollback, document post-mortem","Blame QA","Log it for later"],
      "Immediately notify team, assess impact, implement fix/rollback, document post-mortem","Transparent, fast incident response is professional maturity."),
    q(R4,"SITUATIONAL","medium","Two senior stakeholders give you conflicting instructions. You:",
      ["Follow the senior one","Acknowledge both, seek alignment meeting, surface trade-offs, get written decision","Flip a coin","Ignore both"],
      "Acknowledge both, seek alignment meeting, surface trade-offs, get written decision","Conflict resolution through structured alignment is key."),
    q(R4,"SITUATIONAL","hard","You believe your manager made a wrong technical decision. You:",
      ["Publicly challenge","Privately share data-backed concerns, propose alternative, accept final decision professionally","Say nothing","Go above them"],
      "Privately share data-backed concerns, propose alternative, accept final decision professionally","Disagree and commit after voicing objection respectfully."),
    q(R4,"SITUATIONAL","hard","You are halfway through a project and requirements change drastically. You:",
      ["Refuse to change","Assess impact, communicate timeline/cost implications, plan incremental pivot, adapt"],
      "Assess impact, communicate timeline/cost implications, plan incremental pivot, adapt",
      "Agility and proactive communication under change is a top professional skill."),
    q(R4,"SITUATIONAL","medium","A client is extremely unhappy. You:",
      ["Transfer call","Listen actively, acknowledge feelings, apologize, explain corrective action, follow up","Argue","Offer refund only"],
      "Listen actively, acknowledge feelings, apologize, explain corrective action, follow up","Empathy + accountability + action is the client service formula."),
    q(R4,"SITUATIONAL","easy","You are asked to work overtime on a personal milestone day. You:",
      ["Refuse all overtime","Assess urgency, negotiate timing, offer alternative solution, be transparent","Always say yes","Always say no"],
      "Assess urgency, negotiate timing, offer alternative solution, be transparent","Professional boundaries with solutions show maturity."),
    q(R4,"CULTURE_FIT","easy","What does a culture of continuous learning mean to you?",
      ["Only attending training","Proactively seeking feedback, experimenting, sharing knowledge, embracing failure as learning","Reading company blogs","Annual certification"],
      "Proactively seeking feedback, experimenting, sharing knowledge, embracing failure as learning","Growth culture = psychological safety + curiosity."),
    q(R4,"CULTURE_FIT","easy","How do you contribute to team morale?",
      ["I don't focus on this","Acknowledge wins, support colleagues, communicate clearly, bring energy and humor","Work alone","Do my tasks only"],
      "Acknowledge wins, support colleagues, communicate clearly, bring energy and humor","Team culture is built by consistent positive micro-behaviors."),
    q(R4,"CULTURE_FIT","medium","How do you approach diversity and inclusion?",
      ["Don't have opinion","Actively seek diverse perspectives, call out bias, advocate for psychological safety","It's HR's job","Tolerance only"],
      "Actively seek diverse perspectives, call out bias, advocate for psychological safety","D&I = active participation, not passive tolerance."),
    q(R4,"CULTURE_FIT","medium","What does work-life integration mean to you?",
      ["Always available","Managing energy sustainably across domains; setting boundaries while delivering results","Never work after hours","Strict separation"],
      "Managing energy sustainably across domains; setting boundaries while delivering results","Modern orgs value sustainable performance, not burnout."),
    q(R4,"CULTURE_FIT","hard","Describe your personal values and how they align with this role.",
      ["I have no values","Reflect genuine values (integrity, growth, collaboration) with specific behavioral evidence","Just say company values","Copy job description"],
      "Reflect genuine values (integrity, growth, collaboration) with specific behavioral evidence","Authentic value alignment predicts cultural retention."),
    q(R4,"CULTURE_FIT","hard","How do you handle a situation where company values conflict with a project decision?",
      ["Ignore company values","Raise the conflict constructively, use values as decision framework, escalate ethically","Quit","Follow orders blindly"],
      "Raise the conflict constructively, use values as decision framework, escalate ethically","Ethical decision making under pressure is a leadership quality."),
    q(R4,"BEHAVIORAL","medium","Tell me about a time you took initiative without being asked.",
      ["I only do what I'm told","STAR: identified opportunity/problem, took action, delivered result beyond expectation","I avoid extra work","It never happened"],
      "STAR: identified opportunity/problem, took action, delivered result beyond expectation","Proactivity and ownership are leadership indicators."),
    q(R4,"BEHAVIORAL","easy","What motivates you at work?",
      ["Only salary","Authentic answer: solving hard problems, impact, growth, team achievement","Benefits","Job security"],
      "Authentic answer: solving hard problems, impact, growth, team achievement","Intrinsic motivation aligns with long-term engagement."),
    q(R4,"SITUATIONAL","medium","Your project scope creeps beyond resources. You:",
      ["Accept all scope","Scope the MVP, negotiate trade-offs, communicate constraints early, document formally","Say yes then deliver less","Deliver nothing"],
      "Scope the MVP, negotiate trade-offs, communicate constraints early, document formally","Scope management: delivery of most business value within constraints."),
    q(R4,"CULTURE_FIT","easy","How do you give constructive feedback to peers?",
      ["I don't give feedback","Use specific situation, describe impact, suggest alternative behavior, follow up","Publicly criticize","Only positive feedback"],
      "Use specific situation, describe impact, suggest alternative behavior, follow up","SBI model: Situation-Behavior-Impact for effective feedback."),
    q(R4,"BEHAVIORAL","hard","Describe a time you had to learn a new technology quickly for a project.",
      ["I avoid new tech","STAR: identified learning path, dedicated focused time, applied immediately, delivered result","I delegated","I delayed project"],
      "STAR: identified learning path, dedicated focused time, applied immediately, delivered result","Rapid learning agility is critical in tech roles."),
    q(R4,"SITUATIONAL","hard","You're leading a project and a key team member leaves mid-way. You:",
      ["Cancel project","Reassess resources, redistribute work, communicate revised timeline, upskill remaining team, consider contracting","Quit too","Panic"],
      "Reassess resources, redistribute work, communicate revised timeline, upskill remaining team, consider contracting","Resilience and resourcefulness under constraint define leadership."),
    q(R4,"CULTURE_FIT","medium","What does psychological safety in a team mean to you?",
      ["No deadlines","An environment where team members can speak up, take risks, and admit mistakes without fear","Only positive feedback","All decisions are safe"],
      "An environment where team members can speak up, take risks, and admit mistakes without fear","Psychological safety (Amy Edmondson) is the #1 predictor of team performance."),
    q(R4,"BEHAVIORAL","medium","How do you balance quality with speed?",
      ["Always sacrifice quality","Define 'good enough' for context, prioritize high-risk areas, use automated testing, iterate","Always slow and perfect","Guess"],
      "Define 'good enough' for context, prioritize high-risk areas, use automated testing, iterate","Quality-speed balance requires context and risk judgment."),
    q(R4,"BEHAVIORAL","easy","What are your strengths?",
      ["I have none","Specific double-verified strengths with behavioral evidence, relevant to role","Generic 'hardworking'","List from job description"],
      "Specific double-verified strengths with behavioral evidence, relevant to role","Strengths backed by stories are more credible than labels."),
    q(R4,"BEHAVIORAL","medium","What is your biggest weakness?",
      ["I have no weaknesses","Genuine weakness with active mitigation strategy showing self-awareness","Strength reframed as weakness","Irrelevant trait"],
      "Genuine weakness with active mitigation strategy showing self-awareness","Interviewers look for self-awareness and growth commitment."),
    q(R4,"CULTURE_FIT","hard","How would you describe your leadership style?",
      ["Authoritarian","Situational: adapt style to team needs; coach vs direct based on maturity/motivation","Laissez-faire always","Micromanage"],
      "Situational: adapt style to team needs; coach vs direct based on maturity/motivation","Situational leadership adapts to follower readiness level."),
    q(R4,"BEHAVIORAL","hard","Describe a time you disagreed with your team's decision but supported it.",
      ["I never disagree","STAR: voice objection with data, decision made, aligned publicly even while disagreeing privately","I sabotaged it","I left the team"],
      "STAR: voice objection with data, decision made, aligned publicly even while disagreeing privately","Disagree and commit = Amazon leadership principle."),
    q(R4,"SITUATIONAL","medium","How would you onboard to a new team effectively?",
      ["Wait to be told","Listen first, map stakeholders, understand goals, deliver quick win within 30 days, build trust","Change everything","Replicate old team culture"],
      "Listen first, map stakeholders, understand goals, deliver quick win within 30 days, build trust","'First 90 days' approach: observe, connect, then act."),
    q(R4,"CULTURE_FIT","easy","Why is teamwork important in a tech company?",
      ["It's not important","Complex problems require diverse cognitive approaches; shared ownership drives better outcomes","To share blame","Mandatory policy"],
      "Complex problems require diverse cognitive approaches; shared ownership drives better outcomes","Collective intelligence outperforms individual expertise on complex challenges."),
    q(R4,"BEHAVIORAL","medium","Tell me about a time you mentored someone.",
      ["I never mentor","STAR: identified growth need, provided structured guidance, tracked progress, celebrated wins","I delegate all teaching","I have no time for mentoring"],
      "STAR: identified growth need, provided structured guidance, tracked progress, celebrated wins","Mentoring shows leadership maturity and investment in team growth."),
    q(R4,"SITUATIONAL","hard","You find your company is doing something ethically questionable. You:",
      ["Ignore it","Raise internally through appropriate channels with documentation; escalate externally if unresolved","Leak to media immediately","Quit silently"],
      "Raise internally through appropriate channels with documentation; escalate externally if unresolved","Ethical leadership: exhaust internal channels first, document everything."),
    q(R4,"CULTURE_FIT","medium","How do you stay current with industry trends?",
      ["I don't bother","Read industry blogs, attend meetups, build side projects, engage with open source, follow thought leaders","Ask manager","Company training only"],
      "Read industry blogs, attend meetups, build side projects, engage with open source, follow thought leaders","Continuous learning is a core professional responsibility."),
    q(R4,"BEHAVIORAL","hard","How do you manage stakeholder expectations on a delayed project?",
      ["Hide the delay","Communicate early with root cause, revised timeline, mitigation plan, and risk log","Send update when done","Blame team"],
      "Communicate early with root cause, revised timeline, mitigation plan, and risk log","Proactive transparent communication preserves trust even in bad news."),
]


class Command(BaseCommand):
    help = 'Seed 200 professional questions into QuestionBank (50 per round)'

    def handle(self, *args, **kwargs):
        created = 0
        skipped = 0

        for qdata in QUESTIONS:
            obj, was_created = QuestionBank.objects.get_or_create(
                round=qdata['round'],
                question_text=qdata['question_text'],
                defaults={
                    'category':       qdata.get('category', 'LOGICAL'),
                    'difficulty':     qdata.get('difficulty', 'medium'),
                    'options':        qdata.get('options', []),
                    'correct_answer': qdata.get('correct_answer', ''),
                    'explanation':    qdata.get('explanation', ''),
                    'starter_code':   qdata.get('starter_code', ''),
                    'expected_output':qdata.get('expected_output', ''),
                    'is_coding':      qdata.get('is_coding', False),
                    'is_active':      True,
                }
            )
            if was_created:
                created += 1
            else:
                skipped += 1

        counts = {}
        for r, _ in QuestionBank.ROUND_CHOICES:
            counts[r] = QuestionBank.objects.filter(round=r, is_active=True).count()

        self.stdout.write(self.style.SUCCESS(
            f"\n✅ Question Bank Seeded!\n"
            f"   Created: {created} | Skipped (already exist): {skipped}\n"
            f"   R1 Aptitude:  {counts.get('R1_APTITUDE',0)} questions\n"
            f"   R2 Practical: {counts.get('R2_PRACTICAL',0)} questions\n"
            f"   R3 Technical: {counts.get('R3_TECHNICAL',0)} questions\n"
            f"   R4 HR/Final:  {counts.get('R4_HR',0)} questions\n"
            f"   TOTAL: {sum(counts.values())} questions\n"
        ))
