# Generated by Django 4.2.28 on 2026-02-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blind_hiring',
            field=models.BooleanField(default=False, help_text='Hide candidate names and photos'),
        ),
    ]
