# Generated by Django 4.2.28 on 2026-03-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_blind_hiring'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voice_preference',
            field=models.CharField(choices=[('female', 'Aria (Female)'), ('male', 'Guy (Male)')], default='female', max_length=10),
        ),
    ]
