# Generated by Django 4.2.28 on 2026-03-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_voice_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='model_preference',
            field=models.CharField(choices=[('gemini-2.0-flash', 'Gemini 1.5 Flash (Fast)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (Deep)')], default='gemini-2.0-flash', max_length=20),
        ),
    ]
