# Generated by Django 4.2.28 on 2026-03-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_model_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='professional_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
