# Generated by Django 4.2.28 on 2026-02-12 16:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_interview_completed_interview_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='interview',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('AI_BOT', 'AI Technical Interview (Round 3)'), ('HR_MANUAL', 'HR Interview (Round 4)')], default='AI_BOT', max_length=20),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='passing_score_r1',
            field=models.FloatField(default=70.0, help_text='Passing score for Round 1 (Aptitude)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='passing_score_r2',
            field=models.FloatField(default=70.0, help_text='Passing score for Round 2 (Practical)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('RESUME_SCREENING', 'Resume Screening'), ('RESUME_SELECTED', 'Resume Selected'), ('RESUME_REJECTED', 'Resume Rejected'), ('ROUND_1_PENDING', 'Round 1 Pending (Aptitude)'), ('ROUND_1_PASSED', 'Round 1 Passed'), ('ROUND_1_FAILED', 'Round 1 Failed'), ('ROUND_2_PENDING', 'Round 2 Pending (Practical)'), ('ROUND_2_PASSED', 'Round 2 Passed'), ('ROUND_2_FAILED', 'Round 2 Failed'), ('ROUND_3_PENDING', 'Round 3 Pending (AI Interview)'), ('ROUND_3_PASSED', 'Round 3 Passed'), ('ROUND_3_FAILED', 'Round 3 Failed'), ('HR_ROUND_PENDING', 'HR Round Pending'), ('OFFER_GENERATED', 'Offer Generated'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=30),
        ),
        migrations.AlterField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.application'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_offered', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('offer_file', models.FileField(blank=True, null=True, upload_to='offers/')),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='GENERATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_deadline', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter', to='jobs.application')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('APTITUDE', 'Aptitude Test (Round 1)'), ('PRACTICAL', 'Practical/Coding Test (Round 2)')], max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=100.0)),
                ('passed', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='jobs.application')),
            ],
        ),
    ]
