# Generated by Django 4.2.28 on 2026-02-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application_updated_at_interview_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('AI_BOT', 'AI Technical Interview (Round 3)'), ('AI_HR', 'AI HR Interview (Round 4)')], default='AI_BOT', max_length=20),
        ),
    ]
