# Generated by Django 4.2.28 on 2026-02-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_application_applied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='technology_stack',
            field=models.CharField(choices=[('PYTHON', 'Python/Django'), ('DOTNET', '.NET/C#'), ('JAVA', 'Java/Spring'), ('JAVASCRIPT', 'JavaScript/Node.js'), ('REACT', 'React/Frontend'), ('DATA_SCIENCE', 'Data Science/ML'), ('DEVOPS', 'DevOps/Cloud'), ('GENERAL', 'General IT')], default='GENERAL', help_text='Primary technology for this role', max_length=20),
        ),
    ]
