# Generated by Django 4.2.28 on 2026-02-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobposting_technology_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='technology_stack',
            field=models.CharField(choices=[('PYTHON', 'Python/Django'), ('DOTNET', '.NET/C#'), ('JAVA', 'Java/Spring'), ('JAVASCRIPT', 'JavaScript/Node.js'), ('REACT', 'React/Frontend'), ('ANGULAR', 'Angular'), ('VUE', 'Vue.js'), ('ANDROID', 'Android/Kotlin'), ('FLUTTER', 'Flutter/Dart'), ('IOS', 'iOS/Swift'), ('DATA_SCIENCE', 'Data Science/ML'), ('DEVOPS', 'DevOps/Cloud'), ('PHP', 'PHP/Laravel'), ('RUBY', 'Ruby/Rails'), ('GENERAL', 'General IT')], default='GENERAL', help_text='Primary technology for this role', max_length=20),
        ),
    ]
