# Generated by Django 4.2.28 on 2026-02-14 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0007_alter_jobposting_technology_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('options', models.JSONField(default=list, help_text='List of options for MCQs (JSON format)')),
                ('correct_answer', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PYTHON', 'Python'), ('JAVA', 'Java'), ('JAVASCRIPT', 'JavaScript'), ('SQL', 'SQL'), ('HR', 'HR/Behavioral'), ('APTITUDE', 'Aptitude'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('SCREENSHOT', 'Periodic Screenshot'), ('VIOLATION', 'Violation Snapshot'), ('SUSPICION', 'Suspicious Activity')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='proctoring_logs/')),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_logs', to='jobs.application')),
            ],
        ),
    ]
