# Generated by Django 4.2.28 on 2026-02-16 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_class', models.CharField(default='fas fa-code', help_text='FontAwesome class', max_length=50)),
                ('color', models.CharField(default='#00d2ff', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='jobposting',
            name='technology',
            field=models.ForeignKey(blank=True, help_text='Dynamic Technology Link (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.technology'),
        ),
    ]
