# Generated by Django 4.2.28 on 2026-02-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_technology_jobposting_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name used in code (e.g., 'application_received')", max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body_content', models.TextField(help_text='HTML content. Use Double Curly Braces for variables.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='ai_insights',
            field=models.TextField(blank=True, default='{}', help_text='JSON storing detailed AI analysis (matched/missing keywords)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('RESUME_SCREENING', 'Resume Screening'), ('RESUME_SELECTED', 'Resume Selected'), ('RESUME_REJECTED', 'Resume Rejected'), ('ROUND_1_PENDING', 'Round 1 Pending (Aptitude)'), ('ROUND_1_PASSED', 'Round 1 Passed'), ('ROUND_1_FAILED', 'Round 1 Failed'), ('ROUND_2_PENDING', 'Round 2 Pending (Practical)'), ('ROUND_2_PASSED', 'Round 2 Passed'), ('ROUND_2_FAILED', 'Round 2 Failed'), ('ROUND_3_PENDING', 'Round 3 Pending (AI Interview)'), ('ROUND_3_PASSED', 'Round 3 Passed'), ('ROUND_3_FAILED', 'Round 3 Failed'), ('HR_ROUND_PENDING', 'HR Round Pending'), ('OFFER_GENERATED', 'Offer Generated'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], db_index=True, default='APPLIED', max_length=20),
        ),
    ]
