# Generated by Django 4.2.28 on 2026-02-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='source_of_hire',
            field=models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('INDEED', 'Indeed'), ('WEBSITE', 'Career Site'), ('REFERRAL', 'Referral'), ('AGENCY', 'Agency'), ('OTHER', 'Other')], default='WEBSITE', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_location',
            field=models.CharField(default='Remote', max_length=100),
        ),
    ]
