# Generated by Django 4.2.28 on 2026-03-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_interview_interview_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='aptitude_difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Difficulty level for Aptitude MCQs', max_length=10),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='practical_difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Difficulty level for Practical MCQs', max_length=10),
        ),
    ]
