# Generated by Django 4.2.28 on 2026-03-07 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0016_jobposting_aptitude_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(help_text='Full problem statement (markdown supported)')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='easy', max_length=10)),
                ('category', models.CharField(choices=[('arrays', 'Arrays & Strings'), ('linked_list', 'Linked Lists'), ('trees', 'Trees & Graphs'), ('dp', 'Dynamic Programming'), ('sorting', 'Sorting & Searching'), ('recursion', 'Recursion'), ('sql', 'SQL'), ('python', 'Python Basics'), ('data_science', 'Data Science / ML'), ('os_concepts', 'OS & System Design')], db_index=True, default='python', max_length=20)),
                ('xp_reward', models.IntegerField(default=50, help_text='XP points awarded on solve')),
                ('starter_code', models.JSONField(blank=True, default=dict)),
                ('test_cases', models.JSONField(default=list)),
                ('constraints', models.TextField(blank=True)),
                ('examples', models.JSONField(blank=True, default=list, help_text='[{"input":"...","output":"...","explanation":"..."}]')),
                ('hints', models.JSONField(blank=True, default=list, help_text='["Hint 1", "Hint 2", "Hint 3"]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['order', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python 3'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('sql', 'SQL')], default='python', max_length=20)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted ✅'), ('WRONG', 'Wrong Answer ❌'), ('ERROR', 'Runtime Error ⚠️'), ('PARTIAL', 'Partial ⚡'), ('TIMEOUT', 'Time Limit Exceeded ⏱️')], max_length=20)),
                ('runtime_ms', models.IntegerField(blank=True, null=True)),
                ('test_results', models.JSONField(blank=True, default=list)),
                ('xp_earned', models.IntegerField(default=0)),
                ('hints_used', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to='jobs.candidate')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='jobs.codingchallenge')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_active', models.DateField(blank=True, null=True)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_xp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
