# Generated by Django 4.2.28 on 2026-03-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_codingchallenge_codingsubmission_candidatexp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(help_text='n8n or Zapier Webhook URL')),
                ('event_type', models.CharField(choices=[('NEW_CANDIDATE', 'New Candidate Applied'), ('SHORTLISTED', 'Candidate Shortlisted'), ('HIRED', 'Candidate Hired'), ('HIGH_RISK_GHOST', 'High Ghosting Risk Found'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('SENTIMENT_RED_FLAG', 'Sentiment Red Flag Observed')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_json', models.TextField(help_text='JSON serialized embedding vector')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_record', to='jobs.candidate')),
            ],
        ),
    ]
