# Generated by Django 4.2.28 on 2026-03-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_webhookconfig_candidateembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='github_url',
            field=models.URLField(blank=True, help_text='Public GitHub/GitLab profile', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Personal portfolio or project site', max_length=500, null=True),
        ),
    ]
