# Generated by Django 4.2.28 on 2026-03-07 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_candidate_github_url_candidate_portfolio_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_salary_offer', models.FloatField()),
                ('initial_salary_offer', models.FloatField()),
                ('max_budget', models.FloatField()),
                ('candidate_counter_offer', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Active Negotiation'), ('ACCEPTED', 'Offer Agreed'), ('REJECTED', 'Offer Declined'), ('STALLED', 'Awaiting Human Intervention')], default='OPEN', max_length=20)),
                ('chat_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation', to='jobs.application')),
            ],
        ),
    ]
