# Generated by Django 4.2.28 on 2026-03-07 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0020_negotiationsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical Skills'), ('SOFT_SKILL', 'Soft Skills / Behavioral'), ('LEADERSHIP', 'Leadership & Management'), ('CULTURE_FIT', 'Culture & Values')], default='TECHNICAL', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Competencies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.JSONField(default=list, help_text="List of milestones: [{'title': '...', 'status': 'PENDING/DONE'}]")),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Drafting'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('ai_generated_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_roadmap', to='jobs.application')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_comments', models.TextField(blank=True)),
                ('is_final', models.BooleanField(default=False, help_text='Set to true if this is the definitive hiring decision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='jobs.application')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=3, help_text='Rating from 1-5')),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.competency')),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jobs.evaluationscorecard')),
            ],
        ),
    ]
