# Generated by Django 4.2.28 on 2026-03-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_competency_onboardingroadmap_evaluationscorecard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='time_limit_r1',
            field=models.IntegerField(default=45, help_text='Time limit for Round 1 in minutes'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='time_limit_r2',
            field=models.IntegerField(default=60, help_text='Time limit for Round 2 in minutes'),
        ),
    ]
