# Generated by Django 4.2.28 on 2026-03-08 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_jobposting_time_limit_r1_jobposting_time_limit_r2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('clarity_score', models.FloatField(default=0.0)),
                ('stress_level', models.FloatField(default=0.0)),
                ('honesty_index', models.FloatField(default=0.0)),
                ('detailed_emotions', models.JSONField(default=dict, help_text="Breakdown: {'happy': 0.1, 'anxious': 0.4, ...}")),
                ('key_phrases', models.JSONField(default=list, help_text='Detected significant technical or behavioral phrases')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='jobs.interview')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadmap_data', models.JSONField(default=dict, help_text='AI-generated courses, projects, and milestones')),
                ('summary', models.TextField(blank=True)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_shared_with_candidate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='growth_roadmap', to='jobs.application')),
            ],
        ),
        migrations.CreateModel(
            name='SourcingMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('fit_rationale', models.TextField()),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('notified_recruiter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmaker_hits', to='jobs.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmaker_results', to='jobs.jobposting')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
