# Generated by Django 4.2.28 on 2026-03-08 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0023_sentimentanalysis_growthroadmap_sourcingmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('icon', models.CharField(default='fas fa-bullhorn', max_length=50)),
                ('target_role', models.CharField(choices=[('ALL', 'All Users'), ('RECRUITER', 'Recruiters Only'), ('CANDIDATE', 'Candidates Only')], default='ALL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserUIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_bg_theme', models.CharField(default='midnight-nebula', max_length=50)),
                ('preferred_accent_color', models.CharField(default='#ff3366', max_length=20)),
                ('glass_opacity', models.FloatField(default=0.1)),
                ('animation_speed', models.FloatField(default=1.0)),
                ('enable_particles', models.BooleanField(default=True)),
                ('font_family', models.CharField(default='Inter', max_length=50)),
                ('font_scale', models.FloatField(default=1.0)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiring_accuracy', models.FloatField(default=0.0, help_text='Matches vs Retentions')),
                ('avg_time_to_fill', models.FloatField(default=0.0)),
                ('interview_conversion_rate', models.FloatField(default=0.0)),
                ('ai_efficiency_gain', models.FloatField(default=0.0, help_text='Time saved using SmartRecruit features')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HiringVelocity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('APPLIED', 'Applied'), ('RESUME_SCREENING', 'Resume Screening'), ('RESUME_SELECTED', 'Resume Selected'), ('RESUME_REJECTED', 'Resume Rejected'), ('ROUND_1_PENDING', 'Round 1 Pending (Aptitude)'), ('ROUND_1_PASSED', 'Round 1 Passed'), ('ROUND_1_FAILED', 'Round 1 Failed'), ('ROUND_2_PENDING', 'Round 2 Pending (Practical)'), ('ROUND_2_PASSED', 'Round 2 Passed'), ('ROUND_2_FAILED', 'Round 2 Failed'), ('ROUND_3_PENDING', 'Round 3 Pending (AI Interview)'), ('ROUND_3_PASSED', 'Round 3 Passed'), ('ROUND_3_FAILED', 'Round 3 Failed'), ('HR_ROUND_PENDING', 'HR Round Pending'), ('OFFER_GENERATED', 'Offer Generated'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], max_length=50)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='velocity_logs', to='jobs.application')),
            ],
            options={
                'verbose_name_plural': 'Hiring Velocities',
            },
        ),
        migrations.CreateModel(
            name='CandidateIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_potential', models.FloatField(default=0.0, help_text='AI Predicted growth over 2 years')),
                ('leadership_index', models.FloatField(default=0.0, help_text='Detected leadership traits/mentorship')),
                ('technical_breadth', models.FloatField(default=0.0, help_text='Diversity of technology stack')),
                ('churn_risk_score', models.FloatField(default=0.0, help_text='Calculated based on job hopping/skills')),
                ('innovation_score', models.FloatField(default=0.0, help_text='Evidence of problem-solving/patents/projects')),
                ('sentiment_baseline', models.FloatField(default=0.0, help_text='Average positivity in communication')),
                ('top_competencies', models.JSONField(default=list)),
                ('missing_critical_skills', models.JSONField(default=list)),
                ('career_trajectory', models.TextField(blank=True, help_text='AI summary of career path')),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence', to='jobs.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(max_length=255)),
                ('resource', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('RESUME_PARSER', 'Resume Parsing'), ('JD_ENHANCER', 'JD Enhancement'), ('INTERVIEW_GEN', 'Question Generation'), ('SENTIMENT', 'Sentiment Analysis'), ('MATCHMAKER', 'Matchmaker Bot'), ('ROADMAP', 'Growth Roadmap'), ('DECISION_MATRIX', 'Decision Matrix'), ('CHATBOT', 'Global Assistant')], max_length=50)),
                ('model_used', models.CharField(default='gemini-2.0-flash', max_length=50)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AI Usage Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
