# Generated by Django 4.2.28 on 2026-03-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_announcement_useruiprofile_recruiterperformance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('resource_title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('difficulty', models.CharField(default='Beginner', max_length=20)),
                ('platform', models.CharField(default='SmartRecruit Academy', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProctoringAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_count', models.IntegerField(default=1)),
                ('pose_stability', models.FloatField(default=1.0)),
                ('eye_status', models.CharField(default='LOOKING_CENTER', max_length=50)),
                ('is_impersonation_risk', models.BooleanField(default=False)),
                ('vision_confidence', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_analysis', to='jobs.application')),
            ],
        ),
    ]
