# Generated by Django 4.2.28 on 2026-03-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_candidate_is_passive_sourced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_committee_report',
            field=models.TextField(blank=True, help_text='CrewAI multi-agent debate report and final verdict', null=True),
        ),
    ]
