# Generated by Django 4.2.28 on 2026-03-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_application_ai_committee_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.CreateModel(
            name='SentimentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fearful', 'Fearful'), ('disgusted', 'Disgusted'), ('surprised', 'Surprised'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('score', models.FloatField(default=0.0, help_text='Confidence score 0.0 to 1.0')),
                ('raw_expressions', models.JSONField(blank=True, default=dict, help_text='Full face-api.js expression scores')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_logs', to='jobs.interview')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['interview', 'timestamp'], name='jobs_sentim_intervi_a677bc_idx')],
            },
        ),
    ]
