# Generated by Django 4.2.28 on 2026-03-17 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0028_alter_interview_status_sentimentlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='sentimentlog',
            options={'ordering': ['timestamp'], 'verbose_name': 'Sentiment Log', 'verbose_name_plural': 'Sentiment Logs'},
        ),
        migrations.RemoveIndex(
            model_name='sentimentlog',
            name='jobs_sentim_intervi_a677bc_idx',
        ),
        migrations.RemoveField(
            model_name='candidateembedding',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='candidatexp',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='candidatexp',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='candidatexp',
            name='problems_solved',
        ),
        migrations.RemoveField(
            model_name='candidatexp',
            name='streak_days',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_file',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='response_deadline',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='salary_offered',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='cost_estimate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_role',
            field=models.CharField(blank=True, default='Specialist', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of career history'),
        ),
        migrations.AddField(
            model_name='candidateembedding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateembedding',
            name='model_version',
            field=models.CharField(default='text-embedding-004', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatexp',
            name='achievements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='candidatexp',
            name='last_earned',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='candidatexp',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_letter_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='salary_package',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='details',
            field=models.TextField(blank=True, help_text='Contextual details about the action'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidateembedding',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='jobs.candidate'),
        ),
        migrations.AlterField(
            model_name='candidateembedding',
            name='vector_json',
            field=models.TextField(help_text='JSON serialized dense vector'),
        ),
        migrations.AlterField(
            model_name='candidatexp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='jobs.application'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='designation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offer',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='sentimentlog',
            name='emotion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sentimentlog',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expression_logs', to='jobs.interview'),
        ),
        migrations.AlterField(
            model_name='sentimentlog',
            name='raw_expressions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sentimentlog',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='event_type',
            field=models.CharField(choices=[('CANDIDATE_APPLIED', 'Candidate Applied'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('OFFER_GENERATED', 'Offer Letter Generated'), ('CANDIDATE_HIRED', 'Candidate Hired'), ('RESUME_PARSED', 'Resume Fully Parsed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='url',
            field=models.URLField(help_text='Target URL for n8n or Zapier'),
        ),
    ]
