# Generated by Django 4.2.28 on 2026-03-17 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0029_alter_activitylog_options_alter_sentimentlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentimentlog',
            options={},
        ),
        migrations.RemoveField(
            model_name='sentimentlog',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='sentimentlog',
            name='interview',
        ),
        migrations.RemoveField(
            model_name='sentimentlog',
            name='raw_expressions',
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='context',
            field=models.CharField(blank=True, default='General', help_text='Where this sentiment was captured', max_length=100),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='label',
            field=models.CharField(default='Neutral', help_text='e.g., Positive, Neutral, Negative', max_length=50),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sentimentlog',
            name='score',
            field=models.FloatField(default=0.0, help_text='Sentiment score from AI engine'),
        ),
    ]
