# Generated by Django 4.2.28 on 2026-03-17 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0030_alter_sentimentlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sentimentlog',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='points_earned',
        ),
        migrations.RemoveField(
            model_name='candidateembedding',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='candidateembedding',
            name='model_version',
        ),
        migrations.RemoveField(
            model_name='candidatexp',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='candidatexp',
            name='last_earned',
        ),
        migrations.RemoveField(
            model_name='candidatexp',
            name='level',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_letter_text',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='salary_package',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sentimentlog',
            name='context',
        ),
        migrations.RemoveField(
            model_name='sentimentlog',
            name='label',
        ),
        migrations.RemoveField(
            model_name='sentimentlog',
            name='user',
        ),
        migrations.AddField(
            model_name='candidateembedding',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='candidatexp',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidatexp',
            name='last_active',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatexp',
            name='problems_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatexp',
            name='streak_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_file',
            field=models.FileField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='salary_offered',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='emotion',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fearful', 'Fearful'), ('disgusted', 'Disgusted'), ('surprised', 'Surprised'), ('neutral', 'Neutral')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_logs', to='jobs.interview'),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='raw_expressions',
            field=models.JSONField(blank=True, default=dict, help_text='Full face-api.js expression scores'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('RESUME_SCREENING', 'Resume Screening'), ('RESUME_SELECTED', 'Resume Selected'), ('RESUME_REJECTED', 'Resume Rejected'), ('ROUND_1_PENDING', 'Round 1 Pending (Aptitude)'), ('ROUND_1_PASSED', 'Round 1 Passed'), ('ROUND_1_FAILED', 'Round 1 Failed'), ('ROUND_2_PENDING', 'Round 2 Pending (Practical)'), ('ROUND_2_PASSED', 'Round 2 Passed'), ('ROUND_2_FAILED', 'Round 2 Failed'), ('ROUND_3_PENDING', 'Round 3 Pending (AI Interview)'), ('ROUND_3_PASSED', 'Round 3 Passed'), ('ROUND_3_FAILED', 'Round 3 Failed'), ('HR_ROUND_PENDING', 'HR Round Pending'), ('OFFER_GENERATED', 'Offer Generated'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('REJECTED_TIMEOUT', 'Rejected - Timeout'), ('SOURCED', 'Sourced (Passive)')], db_index=True, default='APPLIED', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateembedding',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_record', to='jobs.candidate'),
        ),
        migrations.AlterField(
            model_name='candidateembedding',
            name='vector_json',
            field=models.TextField(help_text='JSON serialized embedding vector'),
        ),
        migrations.AlterField(
            model_name='candidatexp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_xp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hiringvelocity',
            name='stage',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('RESUME_SCREENING', 'Resume Screening'), ('RESUME_SELECTED', 'Resume Selected'), ('RESUME_REJECTED', 'Resume Rejected'), ('ROUND_1_PENDING', 'Round 1 Pending (Aptitude)'), ('ROUND_1_PASSED', 'Round 1 Passed'), ('ROUND_1_FAILED', 'Round 1 Failed'), ('ROUND_2_PENDING', 'Round 2 Pending (Practical)'), ('ROUND_2_PASSED', 'Round 2 Passed'), ('ROUND_2_FAILED', 'Round 2 Failed'), ('ROUND_3_PENDING', 'Round 3 Pending (AI Interview)'), ('ROUND_3_PASSED', 'Round 3 Passed'), ('ROUND_3_FAILED', 'Round 3 Failed'), ('HR_ROUND_PENDING', 'HR Round Pending'), ('OFFER_GENERATED', 'Offer Generated'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('REJECTED_TIMEOUT', 'Rejected - Timeout'), ('SOURCED', 'Sourced (Passive)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter', to='jobs.application'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='GENERATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='sentimentlog',
            name='score',
            field=models.FloatField(default=0.0, help_text='Confidence score 0.0 to 1.0'),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='event_type',
            field=models.CharField(choices=[('NEW_CANDIDATE', 'New Candidate Applied'), ('SHORTLISTED', 'Candidate Shortlisted'), ('HIRED', 'Candidate Hired'), ('HIGH_RISK_GHOST', 'High Ghosting Risk Found'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('SENTIMENT_RED_FLAG', 'Sentiment Red Flag Observed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='url',
            field=models.URLField(help_text='n8n or Zapier Webhook URL'),
        ),
        migrations.AddIndex(
            model_name='sentimentlog',
            index=models.Index(fields=['interview', 'timestamp'], name='jobs_sentim_intervi_a677bc_idx'),
        ),
    ]
