# Generated by Django 4.2.28 on 2026-03-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_alter_activitylog_options_alter_sentimentlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('R1_APTITUDE', 'Round 1 — Aptitude (Logical, Quantitative, Verbal)'), ('R2_PRACTICAL', 'Round 2 — Practical (Coding + Programming MCQs)'), ('R3_TECHNICAL', 'Round 3 — Technical (CS, System Design, Django/ML)'), ('R4_HR', 'Round 4 — HR / Behavioral (STAR, Culture Fit)')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('LOGICAL', 'Logical Reasoning'), ('QUANTITATIVE', 'Quantitative Aptitude'), ('VERBAL', 'Verbal Ability'), ('PYTHON_CODING', 'Python / Coding'), ('DSA', 'Data Structures & Algorithms'), ('WEB_CODING', 'Web Programming'), ('CS_FUNDAMENTALS', 'CS Fundamentals'), ('SYSTEM_DESIGN', 'System Design'), ('DJANGO_ML', 'Django / Python / ML'), ('BEHAVIORAL', 'Behavioral / STAR'), ('SITUATIONAL', 'Situational Judgment'), ('CULTURE_FIT', 'Culture & Values Fitment')], default='LOGICAL', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(blank=True, help_text='Exact text of correct option, or model answer for open-ended', max_length=500)),
                ('explanation', models.TextField(blank=True, help_text='Why this answer is correct')),
                ('starter_code', models.TextField(blank=True, help_text='Python starter code for coding Qs')),
                ('expected_output', models.CharField(blank=True, max_length=500)),
                ('is_coding', models.BooleanField(default=False, help_text='True if this is a live code execution Q')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question Bank Entry',
                'verbose_name_plural': 'Question Bank',
                'ordering': ['round', 'difficulty'],
                'indexes': [models.Index(fields=['round', 'difficulty', 'is_active'], name='jobs_questi_round_7244d5_idx')],
            },
        ),
    ]
