# Generated by Django 4.2.28 on 2026-03-18 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0032_questionbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_blockchain_verified',
            field=models.BooleanField(default=False, help_text='Global verification status across all credentials'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='verification_hash',
            field=models.CharField(blank=True, help_text='Primary cryptographic link to the decentralized ledger', max_length=255),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_blockchain_verified', models.BooleanField(default=False)),
                ('verification_hash', models.CharField(blank=True, help_text='Transaction hash or Certificate ID on-chain', max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='jobs.candidate')),
            ],
            options={
                'verbose_name_plural': 'Education History',
            },
        ),
        migrations.CreateModel(
            name='BlockchainAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VERIFY_REQUEST', 'Verification Request Init'), ('VERIFY_SUCCESS', 'Verification Successful'), ('VERIFY_FAILURE', 'Verification Failed'), ('TAMPER_DETECTED', 'Hash Mismatch / Tamper Alert')], max_length=50)),
                ('doc_type', models.CharField(default='Degree/Certificate', max_length=100)),
                ('target_hash', models.CharField(max_length=255)),
                ('status_code', models.CharField(default='SUCCESS', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
