# Generated by Django 4.2.28 on 2026-03-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_candidate_is_blockchain_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('go', 'Go'), ('rust', 'Rust'), ('java', 'Java')], default='python', help_text='Primary language for this challenge', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='category',
            field=models.CharField(choices=[('LOGICAL', 'Logical Reasoning'), ('QUANTITATIVE', 'Quantitative Aptitude'), ('VERBAL', 'Verbal Ability'), ('PYTHON_CODING', 'Python / Coding'), ('JS_CODING', 'JavaScript Coding'), ('GOLANG_CODING', 'Go / Backend'), ('RUST_CODING', 'Rust / Systems'), ('JAVA_CODING', 'Java / Enterprise'), ('DSA', 'Data Structures & Algorithms'), ('WEB_CODING', 'Web Programming'), ('CS_FUNDAMENTALS', 'CS Fundamentals'), ('SYSTEM_DESIGN', 'System Design'), ('DJANGO_ML', 'Django / Python / ML'), ('BEHAVIORAL', 'Behavioral / STAR'), ('SITUATIONAL', 'Situational Judgment'), ('CULTURE_FIT', 'Culture & Values Fitment')], default='LOGICAL', max_length=20),
        ),
    ]
