# Generated by Django 4.2.28 on 2026-03-18 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_questionbank_language_alter_questionbank_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoverPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_score', models.FloatField(default=0.0, help_text='Probability of staying with the company (0-100%)')),
                ('technical_stability', models.FloatField(default=0.0, help_text='Consistency in technical assessment performance')),
                ('sentiment_stability', models.FloatField(default=0.0, help_text='Stability of emotional response during interviews')),
                ('behavioral_alignment', models.FloatField(default=0.0, help_text='Match with company culture and values')),
                ('time_efficiency', models.FloatField(default=0.0, help_text='Score based on assessment speed vs accuracy')),
                ('radar_data', models.JSONField(default=dict, help_text='JSON data for Chart.js Radar Map')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk (Stable)'), ('MEDIUM', 'Medium Risk (Neutral)'), ('HIGH', 'High Risk (At-Risk)')], default='MEDIUM', max_length=10)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turnover_prediction', to='jobs.candidate')),
            ],
            options={
                'verbose_name_plural': 'Turnover Predictions',
                'ordering': ['-retention_score'],
            },
        ),
    ]
