# Generated by Django 4.2.28 on 2026-03-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_turnoverprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='code_final',
            field=models.TextField(blank=True, help_text='Final synchronized code from live session'),
        ),
    ]
