# Generated by Django 4.2.28 on 2026-03-18 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_interview_code_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceInterviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField(blank=True)),
                ('ai_evaluation', models.TextField(blank=True, help_text='AI-generated feedback on behavioral traits')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Vocal Confidence Score (0-100)')),
                ('behavioral_traits', models.JSONField(blank=True, default=dict, help_text="Detected traits like 'Leadership', 'Clarity', etc.")),
                ('fitment_summary', models.TextField(blank=True, help_text='AI-generated executive summary for recruiters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_logs', to='jobs.interview')),
            ],
        ),
    ]
