# Generated by Django 4.2.28 on 2026-03-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_voiceinterviewlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('APTITUDE', 'Aptitude Test (Round 1)'), ('PRACTICAL', 'Practical/Coding Test (Round 2)'), ('AI_BOT', 'AI Technical Interview (Round 3)'), ('AI_HR', 'AI HR Interview (Round 4)'), ('BOTANIST', 'Botanist Voice Interview')], default='AI_BOT', max_length=20),
        ),
    ]
