# Generated by Django 4.2.28 on 2026-03-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0038_alter_interview_interview_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voiceinterviewlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='voiceinterviewlog',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='voiceinterviewlog',
            name='fitment_summary',
        ),
        migrations.AddField(
            model_name='candidate',
            name='detected_language',
            field=models.CharField(blank=True, default='English', help_text='Detected language of the resume', max_length=50),
        ),
        migrations.AddField(
            model_name='voiceinterviewlog',
            name='behavioral_fitment_summary',
            field=models.TextField(blank=True, help_text='Auto-generated summary for the recruiter'),
        ),
        migrations.AddField(
            model_name='voiceinterviewlog',
            name='hesitation_count',
            field=models.IntegerField(default=0, help_text="Number of detected 'um', 'uh', or long silence gaps"),
        ),
        migrations.AddField(
            model_name='voiceinterviewlog',
            name='speech_rate',
            field=models.FloatField(default=0.0, help_text='Words per minute'),
        ),
        migrations.AddField(
            model_name='voiceinterviewlog',
            name='vocal_confidence_score',
            field=models.FloatField(default=0.0, help_text='0-100 score based on speech patterns'),
        ),
        migrations.AddField(
            model_name='voiceinterviewlog',
            name='volume_consistency',
            field=models.FloatField(default=0.0, help_text='Stability of volume (0.0=erratic, 1.0=stable)'),
        ),
        migrations.AlterField(
            model_name='voiceinterviewlog',
            name='ai_evaluation',
            field=models.TextField(blank=True, help_text='Gemini evaluation of behavioral traits'),
        ),
        migrations.AlterField(
            model_name='voiceinterviewlog',
            name='transcript',
            field=models.TextField(blank=True, help_text='Full transcription of the voice session'),
        ),
    ]
