# Generated by Django 4.2.28 on 2026-03-18 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0039_alter_voiceinterviewlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_stage', models.CharField(choices=[('APPLIED', 'Applied'), ('RESUME_SCREENING', 'Resume Screening'), ('RESUME_SELECTED', 'Resume Selected'), ('RESUME_REJECTED', 'Resume Rejected'), ('ROUND_1_PENDING', 'Round 1 Pending (Aptitude)'), ('ROUND_1_PASSED', 'Round 1 Passed'), ('ROUND_1_FAILED', 'Round 1 Failed'), ('ROUND_2_PENDING', 'Round 2 Pending (Practical)'), ('ROUND_2_PASSED', 'Round 2 Passed'), ('ROUND_2_FAILED', 'Round 2 Failed'), ('ROUND_3_PENDING', 'Round 3 Pending (AI Interview)'), ('ROUND_3_PASSED', 'Round 3 Passed'), ('ROUND_3_FAILED', 'Round 3 Failed'), ('HR_ROUND_PENDING', 'HR Round Pending'), ('OFFER_GENERATED', 'Offer Generated'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('REJECTED_TIMEOUT', 'Rejected - Timeout'), ('SOURCED', 'Sourced (Passive)')], max_length=20, unique=True)),
                ('external_ats_stage', models.CharField(help_text='Exact stage name in Workday/Greenhouse', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='external_ats_id',
            field=models.CharField(blank=True, help_text='ID of this application in the external ATS (Workday/Greenhouse)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ATSSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('PUSH', 'Outgoing Link'), ('PULL', 'Incoming Webhook')], max_length=10)),
                ('payload', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='jobs.application')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
