# Generated by Django 4.2.28 on 2026-03-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_atssyncconfig_application_external_ats_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-medal', max_length=50)),
                ('rarity', models.CharField(choices=[('STANDARD', 'Standard'), ('EPIC', 'Epic')], default='STANDARD', max_length=20)),
                ('hex_color', models.CharField(default='#00d2ff', max_length=20)),
                ('criteria_json', models.TextField(blank=True, help_text='Internal JSON criteria for automated awards')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='time_taken',
            field=models.DurationField(blank=True, help_text='Time taken to complete the assessment', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='earned_badges',
            field=models.ManyToManyField(blank=True, related_name='winners', to='jobs.badge'),
        ),
    ]
