# Generated by Django 4.2.28 on 2026-03-18 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0041_badge_assessment_time_taken_candidate_earned_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-Binary'), ('NOT_SAY', 'Prefer not to say')], default='NOT_SAY', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='institution_type',
            field=models.CharField(default='Tier-2', help_text='Analyzed for elitism detection', max_length=100),
        ),
        migrations.CreateModel(
            name='BiasAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateTimeField(auto_now_add=True)),
                ('fairness_score', models.FloatField(default=0.0, help_text='Overall rating 0-100')),
                ('disparate_impact_ratio', models.FloatField(default=1.0)),
                ('equal_opportunity_diff', models.FloatField(default=0.0)),
                ('demographics_json', models.JSONField(blank=True, default=dict)),
                ('is_certified', models.BooleanField(default=False, help_text='True if process meets meritocratic standards')),
                ('audit_report', models.TextField(blank=True)),
                ('has_risk', models.BooleanField(default=False)),
                ('risk_details', models.JSONField(blank=True, default=list)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bias_audits', to='jobs.jobposting')),
            ],
            options={
                'ordering': ['-audit_date'],
            },
        ),
    ]
