# Generated by Django 4.2.28 on 2026-03-18 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0042_candidate_date_of_birth_candidate_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDesignAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_json', models.JSONField(default=dict, help_text='Stores Drawflow node and connection data')),
                ('ai_score', models.FloatField(default=0.0)),
                ('ai_analysis', models.TextField(blank=True, help_text='AI breakdown of architectural strengths and weaknesses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_design', to='jobs.application')),
            ],
            options={
                'verbose_name': 'System Design Assessment',
                'verbose_name_plural': 'System Design Assessments',
            },
        ),
    ]
