# Generated by Django 4.2.28 on 2026-03-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_systemdesignassessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='verification_hash',
            new_name='blockchain_hash',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='is_blockchain_verified',
            new_name='is_verified_on_chain',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='verification_hash',
            new_name='blockchain_hash',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='is_blockchain_verified',
            new_name='is_verified_on_chain',
        ),
        migrations.AddField(
            model_name='candidate',
            name='blockchain_tx_id',
            field=models.CharField(blank=True, help_text='Simulated Transaction ID on the ledger', max_length=255),
        ),
        migrations.AddField(
            model_name='interview',
            name='is_flagged_for_cheating',
            field=models.BooleanField(default=False, help_text='Set to True if proctoring violations exceed threshold'),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='frame',
            field=models.TextField(blank=True, help_text='Base64 encoded frame for replay', null=True),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='proctoring_flags',
            field=models.JSONField(blank=True, default=dict, help_text="Violation flags (e.g., {'multiple_faces': True})"),
        ),
    ]
