# Generated by Django 4.2.28 on 2026-03-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0044_rename_verification_hash_candidate_blockchain_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language_requirement',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('JAVA', 'Java'), ('JAVASCRIPT', 'JavaScript'), ('CPP', 'C++'), ('GO', 'Go'), ('RUST', 'Rust'), ('SQL', 'SQL'), ('HR', 'HR/Behavioral'), ('APTITUDE', 'Aptitude'), ('GENERAL', 'General')], default='GENERAL', help_text='Specific language required for this question', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('JAVA', 'Java'), ('JAVASCRIPT', 'JavaScript'), ('CPP', 'C++'), ('GO', 'Go'), ('RUST', 'Rust'), ('SQL', 'SQL'), ('HR', 'HR/Behavioral'), ('APTITUDE', 'Aptitude'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
    ]
