# Generated by Django 4.2.28 on 2026-03-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_question_language_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentlog',
            name='behavioral_score',
            field=models.FloatField(default=0.0, help_text='AI-calculated behavioral fitment score'),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='vocal_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Voice analytics (speech rate, pause density)'),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='voice_transcript',
            field=models.TextField(blank=True, help_text='Transcribed voice response from the candidate', null=True),
        ),
    ]
