# Generated by Django 4.2.28 on 2026-03-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0046_sentimentlog_behavioral_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentlog',
            name='behavioral_fitment_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of behavioral fitment', null=True),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='hesitation_count',
            field=models.IntegerField(default=0, help_text='Detected pauses or fillers'),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='speech_rate',
            field=models.FloatField(default=0.0, help_text='Words per minute'),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='vocal_confidence_score',
            field=models.FloatField(default=0.0, help_text='Confidence percentage based on vocal analysis'),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='volume_consistency',
            field=models.FloatField(default=0.0, help_text='Standard deviation of volume levels'),
        ),
    ]
