# Generated by Django 4.2.28 on 2026-03-19 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0047_sentimentlog_behavioral_fitment_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atssyncconfig',
            name='provider',
            field=models.CharField(choices=[('WORKDAY', 'Workday'), ('GREENHOUSE', 'Greenhouse'), ('LEVER', 'Lever'), ('SAP_SUCCESSFACTORS', 'SAP SuccessFactors')], default='WORKDAY', max_length=50),
        ),
        migrations.AlterField(
            model_name='atssyncconfig',
            name='external_ats_stage',
            field=models.CharField(help_text='Exact stage name in the external ATS', max_length=100),
        ),
        migrations.CreateModel(
            name='ExternalATSMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_system_name', models.CharField(default='Workday', max_length=50)),
                ('external_candidate_id', models.CharField(db_index=True, max_length=255)),
                ('external_application_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_sync_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ats_mapping', to='jobs.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_mappings', to='jobs.candidate')),
            ],
        ),
    ]
