# Generated by Django 4.2.28 on 2026-03-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0048_atssyncconfig_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='pseudonym',
            field=models.CharField(blank=True, help_text='Gamification identity (e.g. CyberNinja77)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='rarity',
            field=models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='STANDARD', max_length=20),
        ),
    ]
