# Generated by Django 4.2.28 on 2026-03-19 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0050_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('msg_type', models.CharField(choices=[('chat', 'Standard Chat'), ('presence', 'Presence Update'), ('vote_up', 'Upvote / Agree'), ('vote_down', 'Downvote / Disagree'), ('flag', 'Proctoring Flag Alert')], default='chat', max_length=20)),
                ('video_timestamp', models.CharField(default='00:00', help_text='Timestamp of the interview when comment was made', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='is_flagged_for_cheating',
            new_name='is_flagged',
        ),
        migrations.AddField(
            model_name='interview',
            name='flag_count',
            field=models.IntegerField(default=0, help_text='Number of detected proctoring violations'),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='jitter',
            field=models.FloatField(default=0.0, help_text='Micro-tremor frequency variation'),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='pitch_variance',
            field=models.FloatField(default=0.0, help_text='Pitch fluctuation'),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='shimmer',
            field=models.FloatField(default=0.0, help_text='Amplitude variation'),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='stress_index',
            field=models.FloatField(default=0.0, help_text='Calculated stress level (0-100)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='fairness_score',
            field=models.FloatField(default=0.0, help_text='Overall rating 0-100'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='is_certified',
            field=models.BooleanField(default=False, help_text='True if process meets meritocratic standards'),
        ),
        migrations.DeleteModel(
            name='BiasAuditLog',
        ),
        migrations.AddField(
            model_name='interviewdiscussion',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='jobs.interview'),
        ),
        migrations.AddField(
            model_name='interviewdiscussion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
