# Generated by Django 4.2.28 on 2026-03-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0051_interviewdiscussion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='candidate_feedback',
            field=models.TextField(blank=True, help_text="Constructive 'Growth Mindset' feedback for candidate", null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='communication_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='application',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='application',
            name='hr_summary',
            field=models.TextField(blank=True, help_text='Executive summary for HR', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='integrity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='application',
            name='problem_solving_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='application',
            name='technical_score',
            field=models.FloatField(default=0.0),
        ),
    ]
