# Generated by Django 4.2.28 on 2026-03-19 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0052_application_candidate_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_probability', models.FloatField(help_text='Expected probability of top performance (0-100)')),
                ('feature_importance_json', models.JSONField(blank=True, help_text='Impact of each metric on the score', null=True)),
                ('gap_analysis_json', models.JSONField(blank=True, help_text='Benchmarking against ideal top performer profile', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_insight', to='jobs.application')),
            ],
        ),
    ]
