# Generated by Django 4.2.28 on 2026-03-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0054_recruiteravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='architecture_schema',
            field=models.TextField(blank=True, help_text='JSON representation of the visual system architecture'),
        ),
        migrations.AddField(
            model_name='interview',
            name='architecture_score',
            field=models.FloatField(default=0.0, help_text='Score graded by AIEngine for the architecture diagram'),
        ),
    ]
