# Generated by Django 4.2.28 on 2026-03-20 19:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0055_interview_architecture_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='audit_date',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='audit_report',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='demographics_json',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='disparate_impact_ratio',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='equal_opportunity_diff',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='fairness_score',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='has_risk',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='is_certified',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='job',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='risk_details',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 20, 19, 20, 16, 186775, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='AI estimated confidence (0.0 to 1.0)'),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='sentiment_label',
            field=models.CharField(blank=True, help_text='Processed sentiment label from AI', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sentimentlog',
            name='stress_level',
            field=models.FloatField(default=0.0, help_text='AI estimated stress level (0.0 to 1.0)'),
        ),
        migrations.AddField(
            model_name='useruiprofile',
            name='high_value_ping_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useruiprofile',
            name='smtp_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BiasAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('fairness_score', models.FloatField(default=0.0, help_text='Overall rating 0-100')),
                ('disparate_impact_ratio', models.FloatField(default=1.0)),
                ('equal_opportunity_diff', models.FloatField(default=0.0)),
                ('demographics_json', models.JSONField(blank=True, default=dict)),
                ('is_certified', models.BooleanField(default=False, help_text='True if process meets meritocratic standards')),
                ('audit_report', models.TextField(blank=True)),
                ('has_risk', models.BooleanField(default=False)),
                ('risk_details', models.JSONField(blank=True, default=list)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bias_audits', to='jobs.jobposting')),
            ],
            options={
                'ordering': ['-audit_date'],
            },
        ),
    ]
