# Generated by Django 6.0.3 on 2026-03-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0056_alter_auditlog_options_remove_auditlog_audit_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Setting identifier e.g. passing_score_r1', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Setting value (stored as string, cast on read)')),
                ('label', models.CharField(blank=True, help_text='Human-readable label shown in admin UI', max_length=200)),
                ('group', models.CharField(default='general', help_text='Setting group for UI grouping', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group', 'key'],
            },
        ),
    ]
