# Generated by Django 6.0.3 on 2026-03-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0057_add_platform_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], db_index=True, default='OPEN', max_length=10),
        ),
    ]
