# Generated by Django 6.0.3 on 2026-03-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0058_alter_jobposting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiteravailability',
            name='timezone_name',
            field=models.CharField(default='Asia/Kolkata', help_text='IANA timezone e.g. Asia/Kolkata, UTC, America/New_York', max_length=50),
        ),
    ]
