# Generated by Django 6.0.3 on 2026-03-24 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0059_add_timezone_to_recruiter_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='e.g. TWILIO_AUTH_TOKEN', max_length=100, unique=True)),
                ('encrypted_value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('last_rotated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condition_type', models.CharField(choices=[('SCORE_ABOVE', 'AI Score Above'), ('STAGE_REACHED', 'Application Stage Reached'), ('VIOLATION_COUNT', 'Proctoring Violations > X')], max_length=50)),
                ('threshold', models.FloatField(blank=True, help_text='Numeric threshold (e.g. 90.0)', null=True)),
                ('target_stage', models.CharField(blank=True, help_text='Target stage for STAGE_REACHED', max_length=50)),
                ('action', models.CharField(choices=[('SEND_WHATSAPP', 'Send WhatsApp Notification'), ('SEND_EMAIL', 'Send Custom Email'), ('TRIGGER_WEBHOOK', 'Fire External Webhook')], max_length=50)),
                ('webhook_url', models.URLField(blank=True, help_text='Required for TRIGGER_WEBHOOK', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='questionbank',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
