# Generated by Django 6.0.3 on 2026-03-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0060_encryptedapikey_triggerrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='proctoring_notes',
            field=models.TextField(blank=True, help_text='Admin notes on proctoring review'),
        ),
        migrations.AddField(
            model_name='interview',
            name='proctoring_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified Violation'), ('FALSE_POSITIVE', 'False Positive'), ('CLEAN', 'No Violation')], default='CLEAN', max_length=20),
        ),
    ]
